nubian_names = [
("nubian_name_01","Amyrteos"),
("nubian_name_02","Ankhmachis"),
("nubian_name_03","Anemhor"),
("nubian_name_04","Aratos"),
("nubian_name_05","Arganos"),
("nubian_name_06","Charias"),
("nubian_name_07","Djedhor"),
("nubian_name_08","Ezena"),
("nubian_name_09","Horemakhet"),
("nubian_name_10","Isocrates"),
("nubian_name_11","Khabbabash"),
("nubian_name_12","Leonippus"),
("nubian_name_13","Lydiadas"),
("nubian_name_14","Manetho"),
("nubian_name_15","Massiva"),
("nubian_name_16","Nakhthoreb"),
("nubian_name_17","Naravas"),
("nubian_name_18","Nefaarud"),
("nubian_name_19","Neferibre"),
("nubian_name_20","Nesisti"),
("nubian_name_21","Nicias"),
("nubian_name_22","Nicodemus"),
("nubian_name_23","Oezalces"),
("nubian_name_24","Oxyntas"),
("nubian_name_25","Pedubast"),
("nubian_name_26","Peneus"),
("nubian_name_27","Perdiccas"),
("nubian_name_28","Philocrates"),
("nubian_name_29","Philotheos"),
("nubian_name_30","Polyperchon"),
("nubian_name_31","Psherenamun"),
("nubian_name_32","Psherenptah"),
("nubian_name_33","Psammuthes"),
("nubian_name_34","Ptolemy"),
("nubian_name_35","Theocritus"),
("nubian_name_36","Therapon"),
("nubian_name_37","Timoleon"),
("nubian_name_38","Xanthos"),
("nubian_name_39","Xenon"),
("nubian_name_40","Zeteres"),
("nubian_name_41","Zosimus"),
("nubian_name_42","Ahmes"),
("nubian_name_43","Ahmose"),
("nubian_name_44","Alarus"),
("nubian_name_45","Amasus"),
("nubian_name_46","Ameny"),
("nubian_name_47","Bakenrenef"),
("nubian_name_48","Cleomenes"),
("nubian_name_49","Euclid"),
("nubian_name_50","Harsiotef"),
("nubian_name_51","Henut"),
("nubian_name_52","Ibi"),
("nubian_name_53","Khabash"),
("nubian_name_54","Lagus"),
("nubian_name_55","Nectanebo"),
("nubian_name_56","Kheperkare"),
("nubian_name_57","Neferkare"),
("nubian_name_58","Nehi"),
("nubian_name_59","Osorkon"),
("nubian_name_60","Pami"),
("nubian_name_end", "end"),

("nubian_female_name_01", "Agape"),
("nubian_female_name_02", "Agathoclea"),
("nubian_female_name_03", "Amanishabheto"),
("nubian_female_name_04", "Antigone"),
("nubian_female_name_05", "Apame"),
("nubian_female_name_06", "Apollonia"),
("nubian_female_name_07", "Aristomache"),
("nubian_female_name_08", "Artemisia"),
("nubian_female_name_09", "Aspacia"),
("nubian_female_name_10", "Athenais"),
("nubian_female_name_11", "Berenice"),
("nubian_female_name_12", "Charis"),
("nubian_female_name_13", "Cleopatra"),
("nubian_female_name_14", "Cynna"),
("nubian_female_name_15", "Demetria"),
("nubian_female_name_16", "Elpis"),
("nubian_female_name_17", "Eirene"),
("nubian_female_name_18", "Eudocia"),
("nubian_female_name_19", "Eunice"),
("nubian_female_name_20", "Euphemia"),
("nubian_female_name_21", "Eurydice"),
("nubian_female_name_22", "Euthalia"),
("nubian_female_name_23", "Hypatia"),
("nubian_female_name_24", "Nysa"),
("nubian_female_name_25", "Oenanthe"),
("nubian_female_name_26", "Olympia"),
("nubian_female_name_27", "Phila"),
("nubian_female_name_28", "Phile"),
("nubian_female_name_29", "Sostrate"),
("nubian_female_name_30", "Stratonice"),
("nubian_female_name_31", "Thais"),
("nubian_female_name_32", "Theophila"),
("nubian_female_name_33", "Thetima"),
("nubian_female_name_34", "Thessaloniki"),
("nubian_female_name_35", "Thorakis"),
("nubian_female_name_36", "Timo"),
("nubian_female_name_37", "Arsinoe"),
("nubian_female_name_38", "Lysandra"),
("nubian_female_name_39", "Kiya"),
("nubian_female_name_40", "Qelhata"),

("nubian_female_name_end", "end"),
]