north_african_names = [
	("north_african_name_01","Amyrteos"),
	("north_african_name_02","Ankhmachis"),
	("north_african_name_03","Anemhor"),
	("north_african_name_04","Aratos"),
	("north_african_name_05","Arganos"),
	("north_african_name_06","Charias"),
	("north_african_name_07","Djedhor"),
	("north_african_name_08","Ezena"),
	("north_african_name_09","Horemakhet"),
	("north_african_name_11","Isocrates"),
	("north_african_name_12","Khabbabash"),
	("north_african_name_13","Leonippus"),
	("north_african_name_14","Lydiadas"),
	("north_african_name_15","Manetho"),
	("north_african_name_16","Massiva"),
	("north_african_name_17","Nakhthoreb"),
	("north_african_name_18","Naravas"),
	("north_african_name_19","Nefaarud"),
	("north_african_name_21","Neferibre"),
	("north_african_name_22","Nesisti"),
	("north_african_name_23","Nicias"),
	("north_african_name_24","Nicodemus"),
	("north_african_name_25","Oezalces"),
	("north_african_name_26","Oxyntas"),
	("north_african_name_27","Pedubast"),
	("north_african_name_28","Peneus"),
	("north_african_name_29","Perdiccas"),
	("north_african_name_31","Philocrates"),
	("north_african_name_32","Philotheos"),
	("north_african_name_33","Polyperchon"),
	("north_african_name_34","Psherenamun"),
	("north_african_name_35","Psherenptah"),
	("north_african_name_36","Psammuthes"),
	("north_african_name_37","Ptolemy"),
	("north_african_name_38","Theocritus"),
	("north_african_name_39","Therapon"),
	("north_african_name_41","Timoleon"),
	("north_african_name_42","Xanthos"),
	("north_african_name_43","Xenon"),
	("north_african_name_44","Zeteres"),
	("north_african_name_45","Zosimus"),
	("north_african_name_46","Ahmes"),
	("north_african_name_47","Ahmose"),
	("north_african_name_48","Alarus"),
	("north_african_name_49","Amasus"),
	("north_african_name_51","Ameny"),
	("north_african_name_52","Bakenrenef"),
	("north_african_name_53","Cleomenes"),
	("north_african_name_54","Euclid"),
	("north_african_name_55","Harsiotef"),
	("north_african_name_56","Henut"),
	("north_african_name_57","Ibi"),
	("north_african_name_58","Khabash"),
	("north_african_name_59","Lagus"),
	("north_african_name_61","Nectanebo"),
	("north_african_name_62","Kheperkare"),
	("north_african_name_63","Neferkare"),
	("north_african_name_64","Nehi"),
	("north_african_name_65","Osorkon"),
	("north_african_name_66","Pami"),
	("north_african_name_67","Petubastis"),
	("north_african_name_68","Teos"),
	("north_african_name_70", "Adherbal"),
	("north_african_name_71", "Bomilcar"),
	("north_african_name_72", "Ezena"),
	("north_african_name_73", "Gauda"),
	("north_african_name_74", "Gulussa"),
	("north_african_name_75", "Hiempsal"),
	("north_african_name_76", "Iampsas"),
	("north_african_name_77", "Jugurtha"),
	("north_african_name_78", "Masinissa"),
	("north_african_name_79", "Massiva"),
	("north_african_name_80", "Mastanabal"),
	("north_african_name_81", "Micipsa"),
	("north_african_name_82", "Nabdalsa"),
	("north_african_name_83", "Naravas"),
	("north_african_name_84", "Oxyntas"),
	("north_african_name_85", "Sypax"),
	("north_african_name_86", "Syphax"),
	("north_african_name_87", "Tacfarinas"),
	("north_african_name_88", "Tychaeus"),
	("north_african_name_89", "Vermina"),
	("north_african_name_90", "Zeteres"),
	("north_african_name_91", "Gala"),
	("north_african_name_92", "Amastan"),
	("north_african_name_93", "Mastan"),
	("north_african_name_end", "end"),
]