britannic_names = [
("britannic_name_01","AccoAddedomarus"),
("britannic_name_02","Adiatuanus"),
("britannic_name_03","Adminius"),
("britannic_name_04","Aiorix"),
("britannic_name_05","Ambicatos"),
("britannic_name_06","Andecombogius"),
("britannic_name_07","Aneroestes"),
("britannic_name_08","Ariovistus"),
("britannic_name_09","Arverus"),
("britannic_name_10","Arvirargus"),
("britannic_name_11","Atis"),
("britannic_name_12","Avitus"),
("britannic_name_13","Bellicianus"),
("britannic_name_14","Bellovesus"),
("britannic_name_15","Boduognatus"),
("britannic_name_16","Boio"),
("britannic_name_17","Boiorix"),
("britannic_name_18","Bolgios"),
("britannic_name_19","Brennus"),
("britannic_name_20","Bricussa"),
("britannic_name_21","Britomaris"),
("britannic_name_22","Brucetius"),
("britannic_name_23","Buite"),
("britannic_name_24","Cailtram"),
("britannic_name_25","Caractacus"),
("britannic_name_26","Carvilius"),
("britannic_name_27","Cassivellaunus"),
("britannic_name_28","Cattulanus"),
("britannic_name_29","Cartorites"),
("britannic_name_30","Catugnatus"),
("britannic_name_31","Cavarinus"),
("britannic_name_32","Cavarus"),
("britannic_name_33","Celatus"),
("britannic_name_34","Cingetorix"),
("britannic_name_35","Coilus"),
("britannic_name_36","Commios"),
("britannic_name_37","Comux"),
("britannic_name_38","Concolitanus"),
("britannic_name_39","Correus"),
("britannic_name_40","Cottius"),
("britannic_name_41","Crixus"),
("britannic_name_42","Cunobelinus"),
("britannic_name_43","Diviciacus"),
("britannic_name_44","Divico"),
("britannic_name_45","Donnus"),
("britannic_name_46","Drappes"),
("britannic_name_47","Dubnovellaunus"),
("britannic_name_48","Dumnacus"),
("britannic_name_49","Ducarius"),
("britannic_name_50","Duratios"),
("britannic_name_51","Dumnocoveros"),
("britannic_name_52","Dumnorix"),
("britannic_name_53","Elitovius"),
("britannic_name_54","Etitovius"),
("britannic_name_55","Epatticus"),
("britannic_name_56","Galan"),
("britannic_name_57","Galba"),
("britannic_name_58","Guiderius"),
("britannic_name_59","Iacus"),
("britannic_name_60","Iccius"),
("britannic_name_61","Immanuentius"),
("britannic_name_62","Inamarcus"),
("britannic_name_63","Inammicus"),
("britannic_name_64","Indutiomarus"),
("britannic_name_65","Kimarcus"),
("britannic_name_66","Lucterius"),
("britannic_name_67","Lugotorix"),
("britannic_name_68","Lutarius"),
("britannic_name_69","Mallaius"),
("britannic_name_70","Mandubracius"),
("britannic_name_71","Marganus"),
("britannic_name_72","Mascelio"),
("britannic_name_73","Orgetorix"),
("britannic_name_74","Prasutagus"),
("britannic_name_75","Segovax"),
("britannic_name_76","Sinatus"),
("britannic_name_77","Sinorix"),
("britannic_name_78","Sisillius"),
("britannic_name_79","Talorc"),
("britannic_name_80","Tasciovanus"),
("britannic_name_81","Tasgetius"),
("britannic_name_82","Taximagulus"),
("britannic_name_83","Teutomalius"),
("britannic_name_84","Tincomarus"),
("britannic_name_85","Togodumnus"),
("britannic_name_86","Vertiscus"),
("britannic_name_87","Venutius"),
("britannic_name_88","Viridorix"),
("britannic_name_89","Vosenius"),
("britannic_name_90","Vodenos"),
("britannic_name_end", "end"),

("britannic_female_name_01", "Aife"),
("britannic_female_name_02", "Airmed"),
("britannic_female_name_03", "Ancasta"),
("britannic_female_name_04", "Banna"),
("britannic_female_name_05", "Billica"),
("britannic_female_name_06", "Boudica"),
("britannic_female_name_07", "Bricta"),
("britannic_female_name_08", "Brenwen"),
("britannic_female_name_09", "Cata"),
("britannic_female_name_10", "Cartimandua"),
("britannic_female_name_11", "Chiomara"),
("britannic_female_name_12", "Damona"),
("britannic_female_name_13", "Diseta"),
("britannic_female_name_14", "Gwendolen"),
("britannic_female_name_15", "Litavis"),
("britannic_female_name_16", "Iamcilla"),
("britannic_female_name_17", "Maeve"),
("britannic_female_name_18", "Verica"),
("britannic_female_name_19", "Cingetessa"),
("britannic_female_name_20", "Conna"),
("britannic_female_name_21", "Catia"),
("britannic_female_name_22", "Carssouna"),
("britannic_female_name_23", "Cunovinna"),
("britannic_female_name_24", "Illica"),
("britannic_female_name_25", "Lovernisca"),
("britannic_female_name_26", "Magunna"),
("britannic_female_name_27", "Lucilia"),
("britannic_female_name_28", "Oconea"),
("britannic_female_name_29", "Ria"),
("britannic_female_name_30", "Rosula"),
("britannic_female_name_31", "Senica"),
("britannic_female_name_32", "Sentica"),
("britannic_female_name_33", "Sulicena"),
("britannic_female_name_34", "Vassura"),
("britannic_female_name_35", "Vinoma"),
("britannic_female_name_36", "Vorvena"),
("britannic_female_name_37", "Urca"),
("britannic_female_name_38", "Veloriga"),
("britannic_female_name_39", "Velibia"),
("britannic_female_name_40", "Totia"),
("britannic_female_name_41", "Titocuna"),
("britannic_female_name_42", "Velbutena"),
("britannic_female_name_43", "Seniciana"),
("britannic_female_name_44", "Senila"),
("britannic_female_name_45", "Vrocata"),
("britannic_female_name_46", "Exuperata"),
("britannic_female_name_47", "Deiana"),
("britannic_female_name_48", "Cunolava"),
("britannic_female_name_49", "Cunsa"),
("britannic_female_name_50", "Aucissa"),
("britannic_female_name_51", "Allauna"),
("britannic_female_name_52", "Alatucca"),
("britannic_female_name_53", "Aessicunia"),
("britannic_female_name_54", "Bodicacia"),
("britannic_female_name_55", "Britivenda"),
("britannic_female_name_56", "Catissena"),
("britannic_female_name_57", "Cantisena"),
("britannic_female_name_58", "Rhiannon"),
("britannic_female_name_59", "Andraste"),
("britannic_female_name_60", "Iouga"),
("britannic_female_name_61", "Ricagambeda"),
("britannic_female_name_62", "Satiada"),
("britannic_female_name_63", "Senuna"),
("britannic_female_name_64", "Sulis"),
("britannic_female_name_65", "Verbeia"),
("britannic_female_name_66", "Modron"),
("britannic_female_name_67", "Arianrhod"),
("britannic_female_name_68", "Goewin"),
("britannic_female_name_69", "Ceridwen"),
("britannic_female_name_70", "Donwen"),
("britannic_female_name_71", "Awen"),
("britannic_female_name_72", "Brigantia"),

("britannic_female_name_end", "end"),
]