roman_names = [
    ("roman_full_names1", "G. Appius Fundus"),
    ("roman_full_names2", "Lucius Lipo"),
    ("roman_full_names3", "Petronius Pasio"),
    ("roman_full_names4", "Marcus Casus"),
    ("roman_full_names5", "Gaius Maximus Dio"),
    ("roman_full_names6", "Quintus Luculus"),
    ("roman_full_names7", "Servius Suplicius"),
    ("roman_full_names8", "Livius Suplicius Camerinus"),
    ("roman_full_namesend", "end"),

    ("name_roman_1", "Primus"),
    ("name_roman_2", "Secundus"),
    ("name_roman_3", "Tertius"),
    ("name_roman_4", "Quartus"),
    ("name_roman_5", "Quintus"),
    ("name_roman_6", "Sextus"),
    ("name_roman_7", "Aurelianus"),
    ("name_roman_8", "Aulus"),
    ("name_roman_9", "Faustus"),
    ("name_roman_10", "Octavius"),
    ("name_roman_11", "Nonus"),
    ("name_roman_12", "Servius"),
    ("name_roman_13", "Manius"),
    ("name_roman_14", "Septimus"),
    ("name_roman_15", "Servius"),
    ("name_roman_16", "Titus"),
    ("name_roman_17", "Agrippa"),
    ("name_roman_18", "Camillus"),
    ("name_roman_19", "Drusus"),
    ("name_roman_20", "Quadus"),
    ("name_roman_21", "Cloelius"),
    ("name_roman_22", "Gaius"),
    ("name_roman_23", "Canidius"),
    ("name_roman_24", "Duilius"),
    ("name_roman_25", "Fannius"),
    ("name_roman_26", "Gavius"),
    ("name_roman_27", "Junius"),
    ("name_roman_28", "Lemonius"),
    ("name_roman_29", "Marcius"),
    ("roman_names_end", "end"),
    ("roman_cognomen_1", "Abito"),
    ("roman_cognomen_2", "Brutus"),
    ("roman_cognomen_3", "Curio"),
    ("roman_cognomen_4", "Dio"),
    ("roman_cognomen_5", "Evodius"),
    ("roman_cognomen_6", "Fadus"),
    ("roman_cognomen_7", "Fagus"),
    ("roman_cognomen_8", "Epimachus"),
    ("roman_cognomen_9", "Horatius"),
    ("roman_cognomen_10", "Hadrianus"),
    ("roman_cognomen_11", "Iuvenalis"),
    ("roman_cognomen_12", "Lepidus"),
    ("roman_cognomen_13", "Marius"),
    ("roman_cognomen_14", "Nepos"),
    ("roman_cognomen_15", "Orosius"),
    ("roman_cognomen_16", "Publianus"),
    ("roman_cognomen_17", "Solianus"),
    ("roman_cognomen_18", "Scipio"),
    ("roman_cognomen_19", "Tiberius"),
    ("roman_cognomen_20", "Ulpianus"),
    ("roman_cognomen_21", "Valens"),
    ("roman_cognomen_22", "Varro"),
    ("roman_cognomen_23", "Valentinus"),
    ("roman_cognomen_24", "Zeno"),
    ("roman_cognomen_25", "Aelius"),
    ("roman_cognomen_26", "Avitus"),
    ("roman_cognomen_27", "Concubinatus"),
    ("roman_cognomen_28", "Luscinius"),
    ("roman_cognomen_29", "Verginius"),
    ("cognomen_ends", "cognomen_ends"),

    ("name_female_roman_01", "Prima"),
    ("name_female_roman_02", "Secunda"),
    ("name_female_roman_03", "Tertia"),
    ("name_female_roman_04", "Quarta"),
    ("name_female_roman_05", "Quinta"),
    ("name_female_roman_06", "Sexta"),
    ("name_female_roman_07", "Aureliana"),
    ("name_female_roman_08", "Aula"),
    ("name_female_roman_09", "Vesuvia"),
    ("name_female_roman_10", "Octavia"),
    ("name_female_roman_11", "Nona"),
    ("name_female_roman_12", "Servia"),
    ("name_female_roman_13", "Mania"),
    ("name_female_roman_14", "Septima"),
    ("name_female_roman_15", "Servia"),
    ("name_female_roman_16", "Tita"),
    ("name_female_roman_17", "Agrippa"),
    ("name_female_roman_18", "Camilla"),
    ("name_female_roman_19", "Livia"),
    ("name_female_roman_20", "Quada"),
    ("name_female_roman_21", "Cloelia"),
    ("name_female_roman_22", "Gaia"),
    ("name_female_roman_23", "Canidia"),
    ("name_female_roman_24", "Duilia"),
    ("name_female_roman_25", "Fannia"),
    ("name_female_roman_26", "Gavia"),
    ("name_female_roman_27", "Junia"),
    ("name_female_roman_28", "Lemonia"),
    ("name_female_roman_29", "Aufidia"),
    ("name_female_roman_end", "end"),
]