caucasian_names = [
("caucasian_name_01", "Smbat"),
("caucasian_name_02", "Khachik"),
("caucasian_name_03", "Ashot"),
("caucasian_name_04", "Arsham"),
("caucasian_name_05", "Zariadres"),
("caucasian_name_06", "Hamazasp"),
("caucasian_name_07", "Vardan"),
("caucasian_name_08", "Artawazd"),
("caucasian_name_09", "Mzez"),
("caucasian_name_10", "Eruand"),
("caucasian_name_11", "Orontes"),
("caucasian_name_12", "Mithranes"),
("caucasian_name_13", "Kherkhes"),
("caucasian_name_14", "Khozrid"),
("caucasian_name_15", "Sames"),
("caucasian_name_16", "Arshames"),
("caucasian_name_17", "Trdat"),
("caucasian_name_18", "Tigran"),
("caucasian_name_19", "Zareh"),
("caucasian_name_20", "Artashes"),
("caucasian_name_21", "Arshak"),
("caucasian_name_22", "Vagharsh"),
("caucasian_name_23", "Khosrow"),
("caucasian_name_24", "Varazdat"),
("caucasian_name_25", "Vasak"),
("caucasian_name_26", "Ashusha"),
("caucasian_name_end", "end"),

("caucasian_female_name_01", "Tigranuhi"),
("caucasian_female_name_02", "Vanuhi"),
("caucasian_female_name_03", "Mihrana"),
("caucasian_female_name_04", "Asatera"),
("caucasian_female_name_06", "Ariazate"),
("caucasian_female_name_07", "Aka"),
("caucasian_female_name_08", "Ghadana"),
("caucasian_female_name_09", "Erato"),
("caucasian_female_name_10", "Zarmandukht"),
("caucasian_female_name_11", "Pharantzem"),
("caucasian_female_name_12", "Mahbanu"),
("caucasian_female_name_13", "Zenobia"),
("caucasian_female_name_14", "Satenik"),

("caucasian_female_end", "end"),
]