roman_names = [
    ("roman_full_names1", "G. Appius Fundus"),
    ("roman_full_names2", "Lucius Lipo"),
    ("roman_full_names3", "Petronius Pasio"),
    ("roman_full_names4", "Marcus Casus"),
    ("roman_full_names5", "Gaius Maximus Dio"),
    ("roman_full_names6", "Quintus Luculus"),
    ("roman_full_names7", "Servius Suplicius"),
    ("roman_full_names8", "Livius Suplicius Camerinus"),
    ("roman_full_namesend", "end"),

    ("roman_name_01", "Primus"),
    ("roman_name_02", "Secundus"),
    ("roman_name_03", "Tertius"),
    ("roman_name_04", "Quartus"),
    ("roman_name_05", "Quintus"),
    ("roman_name_06", "Sextus"),
    ("roman_name_07", "Aurelianus"),
    ("roman_name_08", "Aulus"),
    ("roman_name_09", "Faustus"),
    ("roman_name_10", "Octavius"),
    ("roman_name_11", "Nonus"),
    ("roman_name_12", "Servius"),
    ("roman_name_13", "Manius"),
    ("roman_name_14", "Septimus"),
    ("roman_name_15", "Servius"),
    ("roman_name_16", "Titus"),
    ("roman_name_17", "Agrippa"),
    ("roman_name_18", "Camillus"),
    ("roman_name_19", "Drusus"),
    ("roman_name_20", "Quadus"),
    ("roman_name_21", "Cloelius"),
    ("roman_name_22", "Gaius"),
    ("roman_name_23", "Canidius"),
    ("roman_name_24", "Duilius"),
    ("roman_name_25", "Fannius"),
    ("roman_name_26", "Gavius"),
    ("roman_name_27", "Junius"),
    ("roman_name_28", "Lemonius"),
    ("roman_name_29", "Marcius"),
    ("roman_name_end", "end"),
    ("roman_cognomen_1", "Abito"),
    ("roman_cognomen_2", "Brutus"),
    ("roman_cognomen_3", "Curio"),
    ("roman_cognomen_4", "Dio"),
    ("roman_cognomen_5", "Evodius"),
    ("roman_cognomen_6", "Fadus"),
    ("roman_cognomen_7", "Fagus"),
    ("roman_cognomen_8", "Epimachus"),
    ("roman_cognomen_9", "Horatius"),
    ("roman_cognomen_10", "Hadrianus"),
    ("roman_cognomen_11", "Iuvenalis"),
    ("roman_cognomen_12", "Lepidus"),
    ("roman_cognomen_13", "Marius"),
    ("roman_cognomen_14", "Nepos"),
    ("roman_cognomen_15", "Orosius"),
    ("roman_cognomen_16", "Publianus"),
    ("roman_cognomen_17", "Solianus"),
    ("roman_cognomen_18", "Scipio"),
    ("roman_cognomen_19", "Tiberius"),
    ("roman_cognomen_20", "Ulpianus"),
    ("roman_cognomen_21", "Valens"),
    ("roman_cognomen_22", "Varro"),
    ("roman_cognomen_23", "Valentinus"),
    ("roman_cognomen_24", "Zeno"),
    ("roman_cognomen_25", "Aelius"),
    ("roman_cognomen_26", "Avitus"),
    ("roman_cognomen_27", "Concubinatus"),
    ("roman_cognomen_28", "Luscinius"),
    ("roman_cognomen_29", "Verginius"),
    ("roman_cognomen_end", "cognomen_ends"),

    ("roman_female_name_01", "Prima"),
    ("roman_female_name_02", "Secunda"),
    ("roman_female_name_03", "Tertia"),
    ("roman_female_name_04", "Quarta"),
    ("roman_female_name_05", "Quinta"),
    ("roman_female_name_06", "Sexta"),
    ("roman_female_name_07", "Aureliana"),
    ("roman_female_name_08", "Aula"),
    ("roman_female_name_09", "Vesuvia"),
    ("roman_female_name_10", "Octavia"),
    ("roman_female_name_11", "Nona"),
    ("roman_female_name_12", "Servia"),
    ("roman_female_name_13", "Mania"),
    ("roman_female_name_14", "Septima"),
    ("roman_female_name_15", "Servia"),
    ("roman_female_name_16", "Tita"),
    ("roman_female_name_17", "Agrippa"),
    ("roman_female_name_18", "Camilla"),
    ("roman_female_name_19", "Livia"),
    ("roman_female_name_20", "Quada"),
    ("roman_female_name_21", "Cloelia"),
    ("roman_female_name_22", "Gaia"),
    ("roman_female_name_23", "Canidia"),
    ("roman_female_name_24", "Duilia"),
    ("roman_female_name_25", "Fannia"),
    ("roman_female_name_26", "Gavia"),
    ("roman_female_name_27", "Junia"),
    ("roman_female_name_28", "Lemonia"),
    ("roman_female_name_29", "Aufidia"),
    ("roman_female_name_end", "end"),

    ("roman_female_cognomen_1", "Abita"),
    ("roman_female_cognomen_2", "Bruta"),
    ("roman_female_cognomen_3", "Curia"),
    ("roman_female_cognomen_4", "Dia"),
    ("roman_female_cognomen_5", "Evodia"),
    ("roman_female_cognomen_6", "Fadia"),
    ("roman_female_cognomen_7", "Fagia"),
    ("roman_female_cognomen_8", "Epimachia"),
    ("roman_female_cognomen_9", "Horatia"),
    ("roman_female_cognomen_10", "Hadriania"),
    ("roman_female_cognomen_11", "Iuvenalia"),
    ("roman_female_cognomen_12", "Lepia"),
    ("roman_female_cognomen_13", "Lepitia"),
    ("roman_female_cognomen_14", "Nepitia"),
    ("roman_female_cognomen_15", "Orosia"),
    ("roman_female_cognomen_16", "Publiania"),
    ("roman_female_cognomen_17", "Soliania"),
    ("roman_female_cognomen_18", "Scipia"),
    ("roman_female_cognomen_19", "Tiberia"),
    ("roman_female_cognomen_20", "Ulpiania"),
    ("roman_female_cognomen_21", "Valentia"),
    ("roman_female_cognomen_22", "Paula"),
    ("roman_female_cognomen_23", "Valentinia"),
    ("roman_female_cognomen_24", "Zenia"),
    ("roman_female_cognomen_25", "Aelinia"),
    ("roman_female_cognomen_26", "Avitia"),
    ("roman_female_cognomen_27", "Concubinatia"),
    ("roman_female_cognomen_28", "Luscinia"),
    ("roman_female_cognomen_29", "Verginia"),
    ("roman_female_cognomen_end", "cognomen_ends"),

]