from header_common import *
from header_parties import *
from IDs.ID_troops import *
from IDs.ID_factions import *
from IDs.ID_party_templates import *
from IDs.ID_map_icons import *

#from compiler import *
####################################################################################################################
#  Each party record contains the following fields:
#  1) Party id: used for referencing parties in other files.
#     The prefix p_ is automatically added before each party id.
#  2) Party name.
#  3) Party flags. See header_parties.py for a list of available flags
#  4) Menu. ID of the menu to use when this party is met. The value 0 uses the default party encounter system.
#  5) Party-template. ID of the party template this party belongs to. Use pt_none as the default value.
#  6) Faction.
#  7) Personality. See header_parties.py for an explanation of personality flags.
#  8) Ai-behavior
#  9) Ai-target party
# 10) Initial coordinates.
# 11) List of stacks. Each stack record is a triple that contains the following fields:
#   11.1) Troop-id.
#   11.2) Number of troops in this stack.
#   11.3) Member flags. Use pmf_is_prisoner to note that this member is a prisoner.
# 12) Party direction in degrees [optional]
####################################################################################################################

no_menu = 0

pf_town = pf_is_static|pf_always_visible|pf_show_faction|pf_label_large
pf_castle = pf_is_static|pf_always_visible|pf_show_faction|pf_label_medium
pf_village = pf_is_static|pf_always_visible|pf_hide_defenders|pf_label_small

parties = [
("main_party", "Main Party", pf_limit_members, no_menu, pt_none, fac_player_faction, 0, ai_bhvr_hold, 0, (-48.91, -46.54), [(trp_player, 1, 0)]),

("temp_party", "{!}temp party", pf_disabled, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0, 0), []),
("camp_bandits", "{!}camp bandits", pf_disabled, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (1, 1), [(trp_temp_troop, 3, 0)]),
("temp_party_2", "{!}temp party 2", pf_disabled, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0, 0), []),
("temp_casualties", "{!}casualties", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("temp_casualties_2", "{!}casualties", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("temp_casualties_3", "{!}casualties", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("temp_wounded", "{!}enemies wounded", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("temp_killed", "{!}enemies killed", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("main_party_backup", "{!} ", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("encountered_party_backup", "{!} ", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("collective_friends_backup", "{!} ", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("player_casualties", "{!} ", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("enemy_casualties", "{!} ", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("ally_casualties", "{!} ", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("collective_enemy", "{!}collective enemy", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("collective_ally", "{!}collective ally", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("collective_friends", "{!}collective ally", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("total_enemy_casualties", "{!} ", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("routed_enemies", "{!}routed enemies", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
("zendar", "Zendar", icon_town_alexandria|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (18, 60), []),

("town_1", "Deva", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-220.63, 145.2), [], 170),
("town_2", "Lutetia", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-190.5, 90.31), [], 120),
("town_3", "Augusta", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-269.16, 38.07), [], 80),
("town_4", "Massilia", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-173.82, 38.07), [], 290),
("town_5", "Mediolanum", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-135.05, 55.7), [], 90),
("town_6", "Roma", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-116.52, 20.29), [], 155),
("town_7", "Chersonesus", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (36.69, 77.4), [], 240),
("town_8", "Ancyra", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (58.95, 15.91), [], 175),
("town_9", "Drobeta", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-29.7, 59.33), [], 90),
("town_10", "Tarsus", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (65.42, -9.54), [], 310),
("town_11", "Sarmizegetuza", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-24.63, 78.39), [], 250),
("town_12", "Lugdunum", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-174.59, 68.58), [], 25),
("town_13", "Byzantium", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (8.38, 27.4), [], 60),
("town_14", "Phasis", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (105.19, 60.75), [], 135),
("town_15", "Tulifurdum", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-139.93, 118.98), [], 45),
("town_16", "Philippopolis", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-14.89, 35.2), [], 50),
("town_17", "Tigranocerta", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (114.94, 23.2), [], 190),
("town_18", "Artaxata", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (136.73, 51.39), [], 135),
("town_19", "Hierosolyma", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (86.675, -55.92), [], 45),
("town_20", "Alexandria", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (43.93, -71.02), [], 370),
("town_21", "Cirta", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-190.15, -45.87), [], 330),
("town_22", "Antiochia", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (80.28, -11.96), [], 225),
("town_23", "Lupfurdum", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-113.44, 138.18), [], 225),
("town_24", "Pinnata Castra", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-219.35, 181.52), [], 111),
("town_25", "Tur", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-2.87, 120.03), [], 225),
("town_26", "Siracena", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (113.19, 110.92), [], 225),
("town_27", "Ctesiphon", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (161.6, -19.63), [], 135),
("town_28", "Carthago", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-136.02, -32.02), [], 225),
("town_29", "Leptis Magna", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-92.78, -79.31), [], 225),
("town_30", "Corduba", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-252.63, -6.6), [], 225),
("town_31", "Augusta Emerita", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-270.17, 3.94), [], 225),
("town_32", "Tarraco", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-209.02, 14.57), [], 35),
("town_33", "Tarentum", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-83.39, 8.38), [], 225),
("town_34", "Neapolis", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-104.77, 11.83), [], 225),
("town_35", "Thessalonica", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-34.88, 15.11), [], 225),
("town_36", "Dyrrachium", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-61.55, 8.14), [], 225),
("town_37", "Athenae", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-24.51, -11.52), [], 225),
("town_38", "Nicomedia", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (17.49, 19.96), [], 225),
("town_39", "Ecbatana", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (168.35, 19.02), [], 225),
("town_40", "Dura Europos", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (127.42, -8.39), [], 225),
("town_41", "Torik", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (79.47, 77.17), [], 225),
("town_42", "Dacidava", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-51.53, 68.01), [], 225),
("town_43", "Durnovaria", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-225.69, 119.24), [], 225),
("town_44", "Lavatinae", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-219.07, 160.73), [], 117),
("town_45", "Uburzis", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-138.39, 99.94), [], 225),
("town_46", "Burdigala", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-218.58, 60.93), [], 225),
("town_47", "Palmyra", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (109.87, -27.79), [], 225),
("town_48", "Thebae", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (82.3, -120.93), [], 187),
("town_49", "Kalissia", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-69.42, 138.61), [], 125),
("town_50", "Mtskheta", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (135.04, 67.39), [], 125),
("town_51", "Nishapur", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (247.06, 53.03), [], 60),
("town_52", "Rhagae", icon_landing_point|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (207.74, 20.85), [], 114),

("castle_1", "Carthago Nova", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-227.06, -16.37), [], 50),
("castle_2", "Gades", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-272.28, -15.38), [], 75),
("castle_3", "Araceli", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-228.91, 33.71), [], 100),
("castle_4", "Vindobona", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-89.01, 87.67), [], 180),
("castle_5", "Eboracum", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-212.44, 152.38), [], 90),
("castle_6", "Siracusae", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-95.15, -29.95), [], 55),
("castle_7", "Netindava", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-32.34, 106.46), [], 45),
("castle_8", "Flevum", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-168.29, 140.32), [], 30),
("castle_9", "Augusta Vindelicorum", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-113.17, 92.97), [], 100),
("castle_10", "Durocortorum", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-178.17, 100.39), [], 110),
("castle_11", "Genua", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-142.99, 46.88), [], 75),
("castle_12", "Carnuntum", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-78.61, 83.8), [], 95),
("castle_13", "Novae", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-25.05, 46.72), [], 115),
("castle_14", "Venonis", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-215.77, 130.47), [], 90),
("castle_15", "Tomis", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (0.56, 52.74), [], 235),
("castle_16", "Colonia Agrippina", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-162.37, 122.14), [], 45),
("castle_17", "Tiras", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (7.88, 80.21), [], 15),
("castle_18", "Petrodava", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-18.42, 88.76), [], 300),
("castle_19", "Potaissa", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-69.31, 81.12), [], 280),
("castle_20", "Heraclea", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-62.29, 57.56), [], 260),
("castle_21", "Olbia", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (21.69, 89.71), [], 260),
("castle_22", "Nuithonum", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-132.96, 137.72), [], 260),
("castle_23", "Londinium", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-207.41, 126.99), [], 80),
("castle_24", "Mogontiacum", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-159.8, 114.09), [], 260),
("castle_25", "Cytaea", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (120.58, 71), [], 260),
("castle_26", "Apsaros", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (102.56, 50.6), [], 260),
("castle_27", "Polemonion", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (64.2, 43.35), [], 260),
("castle_28", "Melitene", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (88.29, 22.42), [], 260),
("castle_29", "Viminacium", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-47, 50.82), [], 280),
("castle_30", "Arbela", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (136.02, 10.76), [], 260),
("castle_31", "Miletus", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (4.86, -8.88), [], 260),
("castle_32", "Sirmium", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-83.92, 96.56), [], 260),
("castle_33", "Ekolisma", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-94.77, 97.8), [], 80),
("castle_34", "Augusta Raurica", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-145.54, 83.51), [], 260),
("castle_35", "Salona", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-82.381, 39.014), [], 260),
("castle_36", "Treva", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-145.17, 147.06), [], 260),
("castle_37", "Troesmis", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-0.850, 63.50), [], 260),
("castle_38", "Arsamosata", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (111.46, 38.77), [], 260),
("castle_39", "Singidunum", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-82.59, 59.75), [], 280),
("castle_40", "Edessa", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (116.59, -6.88), [], 260),
("castle_41", "Cyrene", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-40.31, -70.71), [], 260),
("castle_42", "Samosata", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (102.12, 8.38), [], 80),
("castle_43", "Utica", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-156.96, -43.98), [], 260),
("castle_44", "Masada", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (89.54, -64.41), [], 260),
("castle_45", "Jotapata", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (86.5, -37.69), [], 260),
("castle_46", "Ceasarea", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (80.21, -45.69), [], 260),
("castle_47", "Petra", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (94.17, -72.49), [], 80),
("castle_48", "Phraspa", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (154.36, 22.06), [], 80),
("castle_49", "Tulisurquium", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-152.84, 121.22), [], 260),
("castle_50", "Lugidunum", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-114.99, 108.39), [], 260),
("castle_51", "Budorgis", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-94.96, 125.12), [], 260),
("castle_52", "Silingum", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-77.97, 122.31), [], 200),
("castle_53", "Rhetindovinum", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-118.17, 98.53), [], 260),
("castle_54", "Hara", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (163.3, 43.56), [], 100),
("castle_55", "Charax Spasinu", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (195.34, -28.49), [], 250),
("castle_56", "Cababtaca", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (123.4, 93.53), [], 45),
("castle_57", "Camulodunum", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-196.24, 130.82), [], 120),
("castle_58", "Bodotria", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-230.26, 187.01), [], 35),
("castle_59", "Oium", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-27.39, 121.64), []),
("castle_60", "Truso", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-74.87, 159.05), []),
("castle_61", "Caralis", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-142.08, -5.86), []),
("castle_62", "Salamis", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (62.5, -26.05), []),
("castle_63", "Cnossus", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-5.41, -39.03), []),
("castle_64", "Tingis", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-271.83, -37.27), []),
("castle_65", "Susa", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (193.49, -11.09), []),
("castle_66", "Themiskyra", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (34.49, 109.53), []),
("castle_67", "Porulissum", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-58.03, 85.5), []),
("castle_68", "Derbent", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (140.49, 90.53), []),
("castle_69", "Shamakha", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (159.49, 65.53), []),
("castle_70", "Alashkert", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (124.49, 44.53), []),
("castle_71", "Phanagoria", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (61.44, 83.37), []),
("castle_72", "Sebatum", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-117.44, 71.37), []),
("castle_73", "Veldidena", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-130.03, 76.58), []),
("castle_74", "Istakhr", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (244.14, -24.25), []),
("castle_75", "Tabae", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (235.91, 1.25), []),
("castle_76", "Elymais", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (214.3, -4.15), []),
("castle_77", "Karbayagan", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (199.91, 9), []),
("castle_78", "Doclea", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-60, 38), []),
("castle_79", "Hormirzad", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (291, -27), []),
("castle_80", "Meyaneh", icon_landing_point|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (174.88, 31.74), []),

("village_1", "Pengwern", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-227.3, 129), [], 100),
("village_2", "Seria Fama Iulia", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-274.1, -3.34), [], 110),
("village_3", "Lindum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-206.52, 146.67), [], 130),
("village_4", "Pax Iulia", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-288.28, -5.33), [], 130),
("village_5", "Isca Dumnoniorum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-236.76, 117.67), [], 170),
("village_6", "Cecilionicum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-251.07, 21.79), [], 100),
("village_7", "Murgis", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-238.07, -24.07), [], 110),
("village_8", "Pola", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-103.3, 64.23), [], 170),
("village_9", "Turla", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (11.8, 110.05), [], 120),

("village_10", "Dubris", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-198.4, 121.83), [], 120),
("village_11", "Clepidava", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (5.82, 88.84), [], 100),
("village_12", "Nymphaion", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (35.99, 82.53), [], 110),
("village_13", "Valentia", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-220.58, -1.17), [], 120),
("village_14", "Larnum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-198.03, 19.57), [], 130),
("village_15", "Juliobona", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-198.77, 106.34), [], 170),
("village_16", "Kabillon", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-107.13, 105.64), [], 170),
("village_17", "Mursa", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-80.33, 72.36), [], 35),
("village_18", "Vizontion", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-29.48, 99.48), [], 170),
("village_19", "Tirana", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-57.23, 94.25), [], 170),
("village_20", "Parca", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-56, 60.76), [], 170),
("village_21", "Tamasidava", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-8.09, 74.08), [], 100),
("village_22", "Toms", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1.5, 72.78), [], 110),
("village_23", "Vendella", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-243.3, 30.11), [], 120),
("village_24", "Paesici", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-257.19, 46.18), [], 130),
("village_25", "Tanais", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (64.85, 106.07), [], 170),
("village_26", "Avionum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-128.97, 146.98), [], 170),
("village_27", "Mederiacum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-172.24, 122.65), [], 170),
("village_28", "Panticapeum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (54.2, 81.5), [], 170),
("village_29", "Emporiae", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-190.86, 26.16), [], 170),
("village_30", "Vienna", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-174.48, 62.59), [], 170),
("village_31", "Aquae Tarbellicae", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-221.37, 47.16), [], 100),
("village_32", "Novioregum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-217.34, 69.7), [], 110),
("village_33", "Stobensium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-38.72, 23.66), [], 120),
("village_34", "Noviomagus", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-207.74, 99.76), [], 130),
("village_35", "Condivincum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-223.74, 80.26), [], 170),
("village_36", "Narbo Martius", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-188.96, 37.78), [], 170),
("village_37", "Borysthenes", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (31.19, 91.83), [], 170),
("village_38", "Nemetacum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-186.34, 112.01), [], 170),
("village_39", "Batiana", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-174.93, 51.84), [], 170),
("village_40", "Peshmi", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-45.15, 80.4), [], 170),
("village_41", "Plotinopolis", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-6.7, 23.46), [], 100),
("village_42", "Orestia", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-14.03, 28.06), [], 110),
("village_43", "Pompeiopolis", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (56.22, 31.84), [], 120),
("village_44", "Trapezus", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (93.55, 41.91), [], 130),
("village_45", "Pergamum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (7.08, 3.82), [], 170),
("village_46", "Aleria", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-156.79, 137.21), [], 170),
("village_47", "Avaricum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-197.56, 79), [], 170),
("village_48", "Tigisis", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-174.81, -34.54), [], 170),
("village_49", "Durostor", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-32.06, 52.67), [], 10),
("village_50", "Olynthus", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-27.34, 10.7), [], 170),
("village_51", "Sidon", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (83.98, -31.72), [], 100),
("village_52", "Sardes", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (27.26, -0.03), [], 110),
("village_53", "Lilybaeum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-115.83, -20.75), [], 120),
("village_54", "Cenabum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-202.29, 87.51), [], 130),
("village_55", "Durobrivae", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-207.27, 137.79), [], 170),
("village_56", "Brundisium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-69.96, 6.24), [], 170),
("village_57", "Potentia", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-92.79, 15.02), [], 170),
("village_58", "Ancona", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-107.5, 28.74), [], 170),
("village_59", "Ienda", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-138.89, 140.31), [], 170),
("village_60", "Ravenna", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-120.67, 47.95), [], 170),
("village_61", "Treverorum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-164.14, 105.18), [], 100),
("village_62", "Ratiaria", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-67.71, 53.4), [], 100),
("village_63", "Eumenia", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (44.58, 0.82), [], 100),
("village_64", "Setuacotum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-126.14, 112.09), [], 100),
("village_65", "Prusa", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (22.79, 11.59), [], 100),
("village_66", "Phabiranum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-150.03, 127.97), [], 100),
("village_67", "Narona", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-10.18, 58.53), [], 100),
("village_68", "Divodurum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-164.07, 97.93), [], 100),
("village_69", "Phoenice", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-54.17, 1.06), [], 100),
("village_70", "Viviscus", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-157.62, 74.6), [], 100),
("village_71", "Sparta", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-35.08, -19.91), [], 20),
("village_72", "Vorganium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-233.78, 90.88), [], 60),
("village_73", "Kidonia", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-13.66, -38.89), [], 55),
("village_74", "Iader", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-91.97, 42.24), [], 15),
("village_75", "Sigidun", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-127.53, 89.13), [], 10),
("village_76", "Zoaranda", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (130.24, 28.19), [], 35),
("village_77", "Augustodunum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-173.28, 80.7), [], 160),
("village_78", "Iuvavum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-101.62, 87.8), [], 180),
("village_79", "Bibacum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-131.86, 105.91), []),
("village_80", "Noviodun", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-129.53, 95.94), [], 40),
("village_81", "Amorium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (59.43, 4.16), [], 20),
("village_82", "Augustonemetum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-185.29, 71.01), [], 60),
("village_83", "Randea", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (120.61, 14.7), [], 55),
("village_84", "Argentorate", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-154.05, 95.97), [], 15),
("village_85", "Iconium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (76.26, 5.81), [], 10),
("village_86", "Naissus", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-43.76, 39.11), [], 35),
("village_87", "Sangara", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (153.54, 55.8), [], 160),
("village_88", "Attalia", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (31.93, -14.13), [], 180),
("village_89", "Utidava", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-35.03, 78.61), []),
("village_90", "Coracesium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (46.86, -13.23), [], 40),
("village_91", "Thapsus", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-131.24, -49.43), [], 20),
("village_92", "Berzobis", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-42.47, 57.63), [], 60),
("village_93", "Sabrata", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (162.8, 28.93), [], 55),
("village_94", "Gordium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (39.31, 19.25), [], 15),
("village_95", "Pelusium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (63.63, -69.21), [], 10),
("village_96", "Hebron", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (82.4, -51.49), [], 35),
("village_97", "Gaza", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (77.42, -63.98), [], 160),
("village_98", "Samaria", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (90.4, -48.69), [], 180),
("village_99", "Circesium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (127.51, -16.81), []),
("village_100", "Tiberias", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (88.8, -42.9), [], 40),
("village_101", "Ea", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-83.76, 106.31), [], 20),
("village_102", "Paretonium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (0.34, -77.67), [], 60),
("village_103", "Hadrumetum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-134.15, -37.65), [], 55),
("village_104", "Hippo Regius", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-159.54, -31.37), [], 15),
("village_105", "Siga", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-219.24, -38.74), [], 10),
("village_106", "Portus Magnus", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-197.38, -33.32), [], 35),
("village_107", "Durostorum", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-6.9, 48.76), [], 160),
("village_108", "Appolonia", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-45.68, -82.63), [], 180),
("village_109", "Elusa", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (85.1, -62.69), []),
("village_110", "Emesa", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (88.27, -20.36), [], 40),
("village_111", "Arsonium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-61.81, 123.87), [], 35),
("village_112", "Vidrium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-88.6, 156.66), [], 60),
("village_113", "Bunitium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-104.28, 148.83), [], 55),
("village_114", "Talavium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-100.28, 137.83), [], 15),
("village_115", "Tava", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-224.26, 196.2), [], 10),

("village_117", "Trimonium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-222.05, 183.61), [], 160),
("village_118", "Klota", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-229.69, 177.32), [], 180),

("village_120", "Azagarium", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-17.2, 116.79), [], 40),
("village_121", "Hygres", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (17.87, 125.22), [], 20),
("village_122", "Gran", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-5.02, 133.16), [], 60),
("village_123", "Sinda", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (84.78, 113.78), [], 55),
("village_124", "Toreta", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (128.53, 56.86), [], 15),
("village_125", "Navaris", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (112.28, 128.85), [], 10),
("village_126", "Archaeopolis", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (108.2, 67.07), [], 35),
("village_127", "Hira", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (174.32, -33.23), [], 160),
("village_128", "Sostra", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (185.63, -27.45), [], 180),
("village_129", "Babylon", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (160.51, -26.98), []),
("village_130", "Kerman", icon_landing_point|pf_is_static|pf_always_visible, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (157.56, -8.77), [], 40),
("village_131", "Sicca Veneria", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-143.95, -44.21), [], 40),
("village_132", "Siptimunicia", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-137.93, -60.96), [], 40),
("village_133", "Hadaura", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-143.25, -27.94), [], 40),
("village_134", "Sabratha", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-114.27, -73.87), [], 40),
("village_135", "Garbia", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-100.42, -79.26), [], 40),
("village_136", "Syrazur", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (155.35, 8.88), [], 40),
("village_137", "Arae Philenorum", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-76.12, -89.33), [], 40),
("village_138", "Hercula", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-264.29, -24.18), [], 40),
("village_139", "Laminium", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-257.16, -12.41), [], 40),
("village_140", "Egitania", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-265.57, 18.21), [], 40),
("village_141", "Metellinum", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-256.46, 4.64), [], 40),
("village_142", "Felicitas Julia", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-292.67, 6.68), [], 40),
("village_143", "Eburobritium", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-283.17, 16.04), [], 40),
("village_144", "Venictia", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-262.8, 30.31), [], 40),
("village_145", "Limia", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-278.81, 29.5), [], 40),
("village_146", "Caesaraugusta", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-220.37, 24.61), [], 40),
("village_147", "Carca", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-235.45, -0.78), [], 40),
("village_148", "Segobriga", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-234.28, 12.82), [], 40),
("village_149", "Cosentia", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-81.12, -3.28), [], 40),
("village_150", "Velia", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-92.58, 4.34), [], 40),
("village_151", "Rhegium", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-89.23, -13.37), [], 40),
("village_152", "Pisae", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-126.35, 36.33), [], 40),
("village_153", "Arretium", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-118.2, 33.32), [], 40),
("village_154", "Frosino", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-102.93, 17.19), [], 40),
("village_155", "Larissa", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-36.09, 0.67), [], 40),
("village_156", "Serdica", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-28.32, 22.15), [], 40),
("village_157", "Amasia", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (77.62, 32.34), [], 40),
("village_158", "Nicopolis", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-18.88, 44.95), [], 40),
("village_159", "Scodra", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-52.82, 16.11), [], 40),
("village_160", "Segestica", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-75.36, 47.58), [], 40),
("village_161", "Corinthus", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-30.39, -13.72), [], 40),
("village_162", "Patrae", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-39.4, -12.42), [], 121),
("village_163", "Tavium", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (85.03, 11.24), [], 40),
("village_164", "Alia", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (89.93, -76.96), [], 40),
("village_165", "Bithynium", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (41.69, 41.25), [], 40),
("village_166", "Ephesus", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (2.55, -2.73), [], 40),
("village_167", "Takrit", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (142.02, -3.62), [], 40),
("village_168", "Hatra", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (142.96, -15.09), [], 40),
("village_169", "Nahavand", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (179.04, 6.12), [], 40),
("village_170", "Riskephas", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (139.84, 20.31), [], 40),
("village_171", "Amia", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (129.06, 5.49), [], 40),
("village_172", "Kish", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (184.09, -18.46), [], 40),
("village_173", "Ebirapa", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (102.27, 97.53), [], 40),
("village_174", "Dioscurias", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (95.51, 71.5), [], 40),
("village_175", "Suruba", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (89, 86.99), [], 40),
("village_176", "Galtis", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-66.18, 70.76), [], 40),
("village_177", "Napoca", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-34.78, 69.91), [], 40),
("village_178", "Sandava", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-20.27, 71.99), [], 40),
("village_179", "Tyritava", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-8.82, 91.7), [], 40),
("village_180", "Sorviodunum", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-217.35, 121.9), [], 40),
("village_181", "Solis", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-229.38, 123.88), [], 40),
("village_182", "Segontium", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-230.76, 142.58), [], 40),
("village_183", "Ratae", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-215.98, 139.37), [], 40),
("village_184", "Epiacum", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-210.1, 158.34), [], 40),
("village_185", "Alaurus", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-216.53, 171.01), [], 40),
("village_186", "Mamercus", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-225.92, 162.82), [], 40),
("village_187", "Solicinium", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-142.53, 92.27), [], 40),
("village_188", "Lupoduman", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-145.11, 105.85), [], 40),
("village_189", "Locoritum", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-138.59, 128.54), [], 40),
("village_190", "Maevium", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-145.08, 115.26), [], 40),
("village_191", "Calancorum", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-113.58, 120), [], 40),
("village_192", "Viadrus", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-95.8, 110.14), [], 40),
("village_193", "Carini", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-124.18, 133), [], 40),
("village_194", "Usbium", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-105.71, 97.38), [], 40),
("village_195", "Virunum", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-98.51, 77.1), [], 40),
("village_196", "Biolindum", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-199.79, 59.38), [], 40),
("village_197", "Tolosa", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-205.92, 42.29), [], 40),
("village_198", "Hierapolis", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (101.3, -1.49), [], 40),
("village_199", "Cyrrhus", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (90.68, 6.68), [], 40),
("village_200", "Thaura", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (114.12, 0.8), [], 40),
("village_201", "Issus", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (87.41, -5.55), [], 40),
("village_202", "Pharbaetus", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (57.16, -68.79), [], 40),
("village_203", "Athribis", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (56.82, -79.98), [], 40),
("village_204", "Heracleopolis", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (50.97, -100.63), [], 40),
("village_205", "Hermopolis", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (44.59, -76.81), [], 40),
("village_206", "Syene", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (85.19, -142.44), [], 40),
("village_207", "Memphis", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (49.83, -89.25), [], 40),
("village_208", "Reudignium", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-129.29, 124.84), [], 40),
("village_209", "Lamoria", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-129.75, 51.84), [], 40),
("village_210", "Venetia", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-121.72, 58.51), [], 40),
("village_211", "Argentum", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-145.52, 53.19), [], 40),
("village_212", "Satala", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (100.27, 31.65), [], 40),
("village_213", "Amazari", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (149.32, 63.55), [], 40),
("village_214", "Armanasa", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (117.35, 51.68), [], 40),
("village_215", "Naxouna", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (134.46, 45.46), [], 40),
("village_216", "Tushpa", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (142, 30.78), [], 40),
("village_217", "Salananias", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (100.76, -16), [], 40),
("village_218", "Gasama", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (98.82, -32.58), [], 90),
("village_219", "Resapha", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (114.46, -20.21), [], 40),
("village_220", "Olana", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (167.47, 56.02), [], 160),
("village_221", "Allsania", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (129.18, 92.0), [], 110),
("village_222", "Ascaullis", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-84.11, 135.73), [], 90),
("village_223", "Bez", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-46.9, 131.31), [], 180),
("village_224", "Carrodunum", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-67.2, 112.42), [], 130),
("village_225", "Altera", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-117.32, 148.61), [], 136),
("village_226", "Aleria", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-142.7, 19.38), [], 136),
("village_227", "Rhodos", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (14.17, -25.25), [], 136),
("village_228", "Rusaddir", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-245.96, -46.62), [], 136),
("village_229", "Palma", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-192.8, -1.7), [], 136),
("village_230", "Hyperboria", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (41.84, 137.13), [], 136),
("village_231", "Brigetio", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-43.78, 90.49), [], 176),
("village_232", "Shaporan", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (153.98, 75.97), [], 176),
("village_233", "Khorsan", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (170.6, 63.32), [], 176),
("village_234", "Zarehavan", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (135.6, 38.32), [], 176),
("village_235", "Amida", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (102.6, 18.32), [], 176),
("village_236", "Uplistsikhe", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (129.6, 67.32), [], 176),
("village_237", "Kacheti", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (138.6, 77.32), [], 176),
("village_238", "Gandzak", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (137.6, 61.32), [], 176),
("village_239", "Gorgippia", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (68.6, 80.32), [], 176),
("village_240", "Teurnia", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-106.6, 74.32), [], 176),
("village_241", "Brigantium", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-138.49, 74.45), [], 176),
("village_242", "Ptolemais", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (63.49, -113.45), [], 176),
("village_243", "Darab-gird", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (260.49, -31.45), [], 176),
("village_244", "Aspadana", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (217.72, 7.12), [], 176),
("village_245", "Orebatis", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (219.49, -28.45), [], 176),
("village_246", "Artemita", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (167.21, -7.84), [], 100),
("village_247", "Fereydunshahr", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (194.51, -2.3), [], 50),
("village_248", "Lissus", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-61, 26), [], 120),
("village_249", "Abiward", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (254, 62), [], 25),
("village_250", "Sarakhs", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (274, 56), [], 192),
("village_251", "Semnan", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (225, 34.8), [], 284),
("village_252", "Sari", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (212.68, 44.14), [], 216),
("village_253", "Birjand", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (274.21, 16.83), [], 348),
("village_254", "Gurgan", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (219.71, 57.59), [], 56),
("village_255", "Bampur", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (303.71, -7.59), [], 134),
("village_256", "Ghazwin", icon_landing_point|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (186.89, 23.33), [], 203),

("salt_mine", "Salt Mine", icon_village_barbarian|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (14.2, -31), []),
("four_ways_inn", "Four Ways Inn", icon_village_barbarian|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (4.8, -39.599998), []),
("test_scene", "test scene", icon_village_barbarian|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (10.8, -19.6), []),
("battlefields", "battlefields", icon_village_barbarian|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (10.8, -16.6), []),
("dhorak_keep", "Dhorak Keep", icon_village_barbarian|pf_village|pf_disabled|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-50, -58), []),

("training_ground", "Training Ground", icon_map_ludus|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (3, -7), []),
("training_ground_1", "Ludus", icon_map_ludus|pf_village|pf_label_medium, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-155.75, -48.88), [], 100),
("training_ground_2", "Ludus", icon_map_ludus|pf_village|pf_label_medium, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-56.8, 46.64), [], 100),
("training_ground_3", "Ludus", icon_map_ludus|pf_village|pf_label_medium, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-122.71, 27.92), [], 100),
("training_ground_4", "Ludus", icon_map_ludus|pf_village|pf_label_medium, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-144.31, 6.73), [], 100),
("training_ground_5", "Ludus", icon_map_ludus|pf_village|pf_label_medium, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-40.81, -18.73), [], 100),
("bridge_1", "Training Field", icon_landing_point|pf_village|pf_disabled|pf_label_medium, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-125.800003, 12.5), [], 100),

("looter_spawn_point", "Disband troops (by placing them on left screen)", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-40.85, -49.71), [(trp_celtic_naked_swordman_vet, 15, 0)]),
("steppe_bandit_spawn_point", "Sarmatia Europaea", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (38.89, 123.08), []),
("steppe_bandit_spawn_point1", "Scythia", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-34.19, 120.45), []),
("steppe_bandit_spawn_point2", "Sarmatia Asiatica", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (91.45, 102), []),
("taiga_bandit_spawn_point", "Moesia", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-54.21, 45.7), []),
("taiga_bandit_spawn_point1", "Illyricum", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-69.103, 29.138), []),
("taiga_bandit_spawn_point2", "Dalmatia",pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-89.63, 48.91), []),
("forest_bandit_spawn_point", "Salmantica",  pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-267.97, 13.67), []),
("forest_bandit_spawn_point1", "Baetica",  pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-251.39, 0.35), []),
("forest_bandit_spawn_point2", "Tarraconensis",  pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-232.39, 21.9), []),
("mountain_bandit_spawn_point", "Nabatea", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (108.03, -92.01), []),
("mountain_bandit_spawn_point1", "Judea", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (85.17, -45.34), []),
("mountain_bandit_spawn_point2", "Arabia Petraea", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (108.17, -55.79), []),
("sea_raider_spawn_point_1", "Asia", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (21.98, 3.71), []),
("sea_raider_spawn_point_12", "Cyrenaica", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-31.48, -79.89), []),
("sea_raider_spawn_point_13", "Pontus", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (43.47, 31.93), []),
("sea_raider_spawn_point_2", "Mauretania", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-206.54, -54.6), []),
("sea_raider_spawn_point_21", "Numidia", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-149.29, -61.56), []),
("sea_raider_spawn_point_23", "Africa", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-115.49, -96.56), []),
("desert_bandit_spawn_point", "Mesopotamia", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (160.9, -37.8), []),
("desert_bandit_spawn_point1", "Syricae Deserta", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (124.86, -34.42), []),
("desert_bandit_spawn_point2", "Arabia", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (133.45, -56.4), []),
("desert_bandit_spawn_point3", "Nubia", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (85.84, -160.56), []),
("egyptian_spawn", "Aegyptus", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (50.39, -105.93), []),
("saka_spawn", "Chorasmia", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0,  (255, 81), []),
("black_sea_pirates_spawn_1", "Mare Euxinum", pf_disabled|icon_landing_point|pf_is_static|pf_label_large|pf_hide_defenders, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0,  (44.785, 75.912), []),

("spawn_points_end", "{!}last spawn point", pf_disabled|pf_is_static, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0, 0), []),

("reserved_1", "Vesuvius", icon_landing_point|pf_no_label|pf_hide_defenders|pf_is_static|pf_always_visible, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (-100.53, 10.9), []),
("reserved_2", "Aetna", icon_landing_point|pf_no_label|pf_hide_defenders|pf_is_static|pf_always_visible, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (-99.72, -20.86), []),
("reserved_3", "{!}last spawn point", pf_disabled|pf_is_static, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0, 0), []),
("reserved_4", "{!}last spawn point", pf_disabled|pf_is_static, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0, 0), []),
("reserved_5", "{!}last spawn point", pf_disabled|pf_is_static, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0, 0), []),

("pillars", "Pillars of Heracles", icon_map_bandit_lair|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-266.52, -35.85), [], 100),
("grave_anatolia", "Grave of Solymus", icon_map_bandit_lair|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (27.52, -16.85), [], 100),
("tarquinii", "Necropolis of Tarquinii", icon_roman_house|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-120.52, 23.85), [], 100),
("underworld", "Claudia's House", icon_roman_house|pf_disabled|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-102.85, -22.08), [], 100),

("forest", "Dark Forest", icon_forest|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-222.84, 136.61), [], 180),
("german_temple_1", "Baduhenna sanctuary", icon_castle_c|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-158.96, 130.59), [], 60),
("german_temple_2", "Dunraz sanctuary", icon_castle_c|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-123.74, 104.27), [], 150),
("german_temple_3", "Frijo sanctuary", icon_castle_c|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-103.27, 126.48), [], 40),
("slavic_holy_side_1", "Sleza", icon_forest|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-90.66, 115.06), [], 136),
("stone_henge", "Andraste sanctuary", icon_map_stone_circle|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-216.61, 124.92), [], 100),
("stone_henge_2", "Maponos sanctuary", icon_map_stone_circle|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-234.9, 133.15), [], 100),
("dacian_holy_side_1", "Temple of Gebeleizis", icon_map_temple|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-25.89, 75.08), [], 92),
("dacian_holy_side_2", "Temple of Zalmoxis", icon_map_temple|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-36.56, 90.24), [], 212),
("sarmatian_holy_side_1", "Altar of Goitosuros", icon_forest|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-3.24, 113.4), [], 180),
("sarmatian_holy_side_2", "Altar of Artimpasa", icon_forest|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (98.49, 119.88), [], 180),
("caucasian_holy_side_1", "Temple of Mihr", icon_map_temple|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (133.84, 53.41), [], 180),
("caucasian_holy_side_2", "Altar of Armazi", icon_forest|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (118.03, 75.53), [], 180),
("persian_holy_side_1", "Fire of Azar Barzin", icon_map_persian_temple|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (260, 47.07), [], 30),
("persian_holy_side_2", "Fire of Bardneshandeh", icon_map_persian_temple|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (204.08, -6.76), [], 268),
("arabian_holy_side_1", "Temple of Al-Lat", icon_map_temple|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (126.98, -107.61), [], 180),
("african_holy_side_1", "Holy cave of Ifri", icon_map_bandit_lair|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-195.79, -55.24), [], 120),
("african_holy_side_2", "Temple of Ammon", icon_map_temple|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-17.92, -128.97), [], 100),
("african_holy_side_3", "Lion-Temple of Apedemak", icon_map_temple|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (105.57, -181.18), [], 152),

("end_temple", "Sandlerland", icon_village_barbarian|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (4.8, -39.599998), []),
("pyramids", "Pyramids", icon_wonder_pyramids_egy|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (45.57, -87.08), []),
("olympia", "Olympia", icon_wonder_parthenon|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-42.06, -15.62), []),
("delphi", "Delphi", icon_map_temple|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-39.56, -5.29), [],180),

("ferry_1a", "ferry station", icon_ferry_station|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (6.31, 26.16), [], 35),
("ferry_2a", "ferry station", icon_ferry_station|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-19.52, -37.15), [], 45),
("ferry_3a", "ferry station", icon_ferry_station|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-204.59, 106.1), []),
("ferry_4a", "ferry station", icon_ferry_station|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-94.12, -16.22), [], 90),
("ferry_5a", "ferry station", icon_ferry_station|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-255.23, -39.66), []),
("ferry_1b", "ferry station", icon_ferry_station|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (12, 21.91), [], 35),
("ferry_2b", "ferry station", icon_ferry_station|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-24.54, -20.77), [], 45),
("ferry_3b", "ferry station", icon_ferry_station|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-206.12, 118.65), []),
("ferry_4b", "ferry station", icon_ferry_station|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-90.41, -16.12), []),
("ferry_5b", "ferry station", icon_ferry_station|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-249.5, -24.69), [], 135),
("transporter", "Transporter", icon_ship|pf_disabled|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (0, 0), [(trp_mercenary_swordsman, 5, 0)]),
("landing_point", "landing point", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-51.69, -43.86), []),
("jetty_1a", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (7.34, 19.46), [], 35),
("jetty_2a", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-20.46, -37.46), [], 45),
("jetty_3a", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-205.47, 104.21), []),
("jetty_4a", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-95.9, -31.47), [], 90),
("jetty_3b", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-207.06, 118.92), []),
("jetty_4c", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-253.36, -40.16), []),
("jetty_5c", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-250.42, -24.89), []),
("jetty_6d", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-143.43, 18.31), []),
("jetty_7e", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-140.73, -6.51), []),
("jetty_8e", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (14.47, -27.2), []),
("jetty_9e", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (64.61, -25.16), []),
("jetty_10e", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (79.95, -44.25), []),
("jetty_11e", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (3.84, -9.54), []),
("jetty_12f", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-196.42, -1), []),
("jetty_13", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (66.42, 44), []),
("jetty_14", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-42.94, -71.81), []),
("jetty_15", "jetty station", icon_landing_point|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (59.45, 83.48), []),
("jetty_end", "jetty station", icon_landing_point|pf_village|pf_disabled|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-129.850006, -18.719999), [], 135),

("follower_party", "Follower Party", icon_town_alexandria_lighthouse|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-23.879999, -71.629997), [], 135),

("lighthouse", "lighthouse", icon_town_alexandria_lighthouse|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (41.58, -71.15), [], 135),

("caves_of_bacchus", "Caves of Dionysus", icon_map_bandit_lair|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-92.95, 20.74), [], 269),
("sacred_grove", "Old grave", icon_map_stone_circle|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-240.74, -15.01), [], 269),
("sacred_grove_2", "Sacred forest", icon_forest|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-137.03, 107.23), [], 180),
("royal_tombs", "Royal Macedonian tombs", icon_forest|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-43.48, 13.68), [], 180),
("mount_olymp", "Mons Olympus", icon_forest|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-38.38, 7.96), [], 180),

("old_mine", "Old mine", icon_forest|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-275.72, 45.67), [(trp_mercenary_swordsman, 50, 0),(trp_hispanic_infantry, 50, 0), (trp_hispanic_heavy_infantry, 50, 0)], 180),
("holy_lance_cave","Montes Sinai", icon_forest_palms|pf_is_static|pf_hide_defenders, no_menu, pt_none, fac_neutral,0,ai_bhvr_hold,0,(78.77, -77.54),[]),
("valley_of_elah","Vallis Elae", icon_forest_palms|pf_is_static|pf_hide_defenders, no_menu, pt_none, fac_neutral,0,ai_bhvr_hold,0,(85.675, -60.00),[]),

("gaetulian_town_1", "Larbas", icon_gaetulian_town|pf_town, no_menu, pt_none, fac_gaetuli, 0, ai_bhvr_hold, 0, (-230.63, -62.98), []),
("garmantian_town_1", "Garama", icon_garamantian_town|pf_town, no_menu, pt_none, fac_garamantes, 0, ai_bhvr_hold, 0, (-110.41, -146.35), []),
("arabian_town_1", "Hegra", icon_arab_town|pf_town, no_menu, pt_none, fac_nabataea, 0, ai_bhvr_hold, 0, (138.4, -115.81), []),
("nubian_town_1", "Meroe", icon_nubian_town|pf_town, no_menu, pt_none, fac_kush, 0, ai_bhvr_hold, 0, (101.97, -187.42), []),
("irish_town_1", "Dun Ailinne", icon_village_barbarian|pf_town, no_menu, pt_none, fac_irish, 0, ai_bhvr_hold, 0,  (-252.73,151.97), []),
("danish_town_1", "Alabu", icon_village_barbarian|pf_town, no_menu, pt_none, fac_danish, 0, ai_bhvr_hold, 0,  (-144.94,165.81), []),
("slavic_town_1", "Gelonos", icon_village_barbarian|pf_town, no_menu, pt_none, fac_slavic, 0, ai_bhvr_hold, 0,  (-41.11,145.88), []),
("georgian_town_1", "Seraca", icon_village_barbarian|pf_town, no_menu, pt_none, fac_georgians, 0, ai_bhvr_hold, 0,  (124.38,80.7), []),
("dahae_town_1", "Kath", icon_village_barbarian|pf_town, no_menu, pt_none, fac_dahae, 0, ai_bhvr_hold, 0,  (233,87), []),

("sartemis", "Hanging Gardens of Babylon", icon_sartemis_icon|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (164.16, -24.18), [], 90),

("island", "Cythnus", icon_map_island|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-16.55, -17.71), [], 90),

("langobard_landing", "Lugian Camp", icon_forest|pf_is_static|pf_always_visible|pf_hide_defenders|pf_label_small|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-80.5,150.9), [], 90),
("kurgan", "Old burial mound", icon_forest|pf_village|pf_hide_defenders|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (276.077, 90.409), [(trp_saka_amazon, 100, 0)], 135),

("vally_of_kings", "Valley of the Kings", icon_valley_of_kings_combined|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (72.67, -124.38), []),
]
