from header_sounds import *

#from compiler import *
sounds = [
   ("click", sf_2d|sf_vol_3,["drum_3.wav"]),
   ("tutorial_1", sf_2d|sf_vol_7|sf_stream_from_hd,["tutorial_1.wav"]),
   ("tutorial_2", sf_2d|sf_vol_1|sf_stream_from_hd,["tutorial_2.wav"]),
   ("gong", sf_2d|sf_priority_9|sf_vol_7|sf_stream_from_hd, ["s_cymbals.wav"]),
   ("quest_taken", sf_2d|sf_priority_9|sf_vol_7|sf_stream_from_hd, []),
   ("quest_completed", sf_2d|sf_priority_9|sf_vol_8|sf_stream_from_hd, ["quest_completed.wav"]),
   ("quest_succeeded", sf_2d|sf_priority_9|sf_vol_6|sf_stream_from_hd, ["quest_succeeded.wav"]),
   ("quest_concluded", sf_2d|sf_priority_9|sf_vol_7|sf_stream_from_hd, ["quest_completed2.wav"]),
   ("quest_failed", sf_2d|sf_priority_9|sf_vol_7|sf_stream_from_hd, ["quest_failed.wav"]),
   ("quest_cancelled", sf_2d|sf_priority_9|sf_vol_7|sf_stream_from_hd, ["quest_cancelled.wav"]),
   ("rain",sf_2d|sf_priority_9|sf_vol_4|sf_looping|sf_stream_from_hd, ["rain_1.wav"]),
   ("money_received",sf_2d|sf_priority_10|sf_vol_4|sf_stream_from_hd, ["coins_dropped_1.wav"]),
   ("money_paid",sf_2d|sf_priority_10|sf_vol_10|sf_stream_from_hd, ["coins_dropped_2.wav"]),
   ("sword_clash_1", sf_priority_5|sf_vol_8,["sword_clank_metal_09.wav","sword_clank_metal_09b.wav","sword_clank_metal_10.wav","sword_clank_metal_10b.wav","sword_clank_metal_12.wav","sword_clank_metal_12b.wav","sword_clank_metal_13.wav","sword_clank_metal_13b.wav"]),
   ("sword_clash_2", sf_priority_5|sf_vol_9,["sword_clash_02.wav"]),
   ("sword_clash_3", sf_priority_5|sf_vol_9,["sword_clash_03.wav"]),
   ("sword_swing", sf_vol_8|sf_priority_2,["s_swordSwing.wav"]),
   ("footstep_grass", sf_priority_1|sf_vol_2, ["man_walk_hard_01.wav", "man_walk_hard_02.wav", "man_walk_hard_03.wav", "man_walk_hard_04.wav", "man_walk_hard_05.wav", "man_walk_hard_06.wav", "man_walk_hard_07.wav", "man_walk_hard_08.wav", "man_walk_hard_09.wav", "man_walk_hard_10.wav"]),
   ("footstep_wood", sf_priority_1|sf_vol_2, ["man_walk_soft_01.wav", "man_walk_soft_02.wav", "man_walk_soft_03.wav", "man_walk_soft_04.wav", "man_walk_soft_05.wav", "man_walk_soft_06.wav", "man_walk_soft_07.wav", "man_walk_soft_08.wav", "man_walk_soft_09.wav", "man_walk_soft_10.wav"]),
   ("footstep_water", sf_vol_4|sf_priority_3,["water_walk_1.wav","water_walk_2.wav","water_walk_3.wav","water_walk_4.wav"]),
   ("footstep_horse",0, ["s_footstep_horse_4b.wav","s_footstep_horse_4f.wav","s_footstep_horse_5b.wav","s_footstep_horse_5f.wav"]),
   ("footstep_horse_1b",sf_priority_3|sf_vol_8, ["s_footstep_horse_4b.wav","s_footstep_horse_4f.wav","s_footstep_horse_5b.wav","s_footstep_horse_5f.wav"]),
   ("footstep_horse_1f",sf_priority_3|sf_vol_8, ["s_footstep_horse_2b.wav","s_footstep_horse_2f.wav","s_footstep_horse_3b.wav","s_footstep_horse_3f.wav"]),
   ("footstep_horse_2b",sf_priority_3|sf_vol_8, ["s_footstep_horse_2b.wav"]),
   ("footstep_horse_2f",sf_priority_3|sf_vol_8, ["s_footstep_horse_2f.wav"]),
   ("footstep_horse_3b",sf_priority_3|sf_vol_8, ["s_footstep_horse_3b.wav"]),
   ("footstep_horse_3f",sf_priority_3|sf_vol_8, ["s_footstep_horse_3f.wav"]),
   ("footstep_horse_4b",sf_priority_3|sf_vol_8, ["s_footstep_horse_4b.wav"]),
   ("footstep_horse_4f",sf_priority_3|sf_vol_8, ["s_footstep_horse_4f.wav"]),
   ("footstep_horse_5b",sf_priority_3|sf_vol_8, ["s_footstep_horse_5b.wav"]),
   ("footstep_horse_5f",sf_priority_3|sf_vol_8, ["s_footstep_horse_5f.wav"]),
   ("jump_begin", sf_vol_6|sf_priority_9,["jump_begin.wav"]),
   ("jump_end", sf_vol_5|sf_priority_9,["jump_end.wav"]),
   ("jump_begin_water", sf_vol_3|sf_priority_9,["jump_begin_water.wav"]),
   ("jump_end_water", sf_vol_3|sf_priority_9,["jump_end_water.wav"]),
   ("horse_jump_begin", sf_vol_6|sf_priority_9,["horse_jump_begin.wav"]),
   ("horse_jump_end", sf_vol_7|sf_priority_9,["horse_jump_end.wav"]),
   ("horse_jump_begin_water", sf_vol_6|sf_priority_9,["jump_begin_water.wav"]),
   ("horse_jump_end_water", sf_vol_6|sf_priority_9,["jump_end_water.wav"]),

   ("release_bow",sf_vol_4, ["release_bow_1.wav"]),
   ("release_crossbow",sf_vol_7, ["release_crossbow_1.wav"]),
   ("release_crossbow_medium",sf_vol_3, ["crossbow_shoot_01.wav","crossbow_shoot_02.wav","crossbow_shoot_03.wav","crossbow_shoot_04.wav","crossbow_shoot_05.wav","crossbow_shoot_06.wav"]),
   ("release_crossbow_far",sf_vol_1, ["crossbow_shoot_01.wav","crossbow_shoot_02.wav","crossbow_shoot_03.wav","crossbow_shoot_04.wav","crossbow_shoot_05.wav","crossbow_shoot_06.wav"]),

   ("throw_javelin",sf_vol_5, ["throw_javelin_2.wav"]),
   ("throw_axe",sf_vol_7, ["throw_axe_1.wav"]),
   ("throw_knife",sf_vol_5, ["throw_knife_1.wav"]),
   ("throw_stone",sf_vol_7, ["throw_stone_1.wav"]),

   ("reload_crossbow",sf_vol_3, []),
   ("reload_crossbow_continue",sf_vol_6, ["put_back_dagger.wav"]),
   ("pull_bow",sf_vol_5, ["pull_bow_1.wav"]),
   ("pull_arrow",sf_vol_5, ["pull_arrow.wav"]),

   ("arrow_pass_by",sf_priority_7, ["arrow_pass_by_1.wav","arrow_pass_by_2.wav","arrow_pass_by_3.wav","arrow_pass_by_4.wav"]),
   ("bolt_pass_by",sf_priority_7, ["bolt_pass_by_1.wav"]),
   ("javelin_pass_by",sf_priority_7, ["javelin_pass_by_1.wav","javelin_pass_by_2.wav"]),
   ("stone_pass_by",sf_vol_9|sf_priority_7, ["stone_pass_by_1.wav"]),
   ("axe_pass_by",sf_priority_7, ["axe_pass_by_1.wav"]),
   ("knife_pass_by",sf_priority_7, ["knife_pass_by_1.wav"]),
   ("bullet_pass_by",sf_priority_7, ["arrow_whoosh_1.wav"]),

   ("incoming_arrow_hit_ground",sf_priority_7|sf_vol_7, ["arrow_hit_ground_2.wav","arrow_hit_ground_3.wav","incoming_bullet_hit_ground_1.wav"]),
   ("incoming_bolt_hit_ground",sf_priority_7|sf_vol_7, ["arrow_hit_ground_2.wav","arrow_hit_ground_3.wav","incoming_bullet_hit_ground_1.wav"]),
   ("incoming_javelin_hit_ground",sf_priority_7|sf_vol_7, ["incoming_javelin_hit_ground_1.wav"]),
   ("incoming_stone_hit_ground",sf_priority_7|sf_vol_7, ["incoming_stone_hit_ground_1.wav"]),
   ("incoming_axe_hit_ground",sf_priority_7|sf_vol_7, ["incoming_javelin_hit_ground_1.wav"]),
   ("incoming_knife_hit_ground",sf_priority_7|sf_vol_7, ["incoming_stone_hit_ground_1.wav"]),
   ("incoming_bullet_hit_ground",sf_priority_7|sf_vol_7, ["incoming_bullet_hit_ground_1.wav"]),

   ("outgoing_arrow_hit_ground",sf_priority_7|sf_vol_7, ["outgoing_arrow_hit_ground.wav"]),
   ("outgoing_bolt_hit_ground",sf_priority_7|sf_vol_7,  ["outgoing_arrow_hit_ground.wav"]),
   ("outgoing_javelin_hit_ground",sf_priority_7|sf_vol_10, ["outgoing_arrow_hit_ground.wav"]),
   ("outgoing_stone_hit_ground",sf_priority_7|sf_vol_7, ["incoming_stone_hit_ground_1.wav"]),
   ("outgoing_axe_hit_ground",sf_priority_7|sf_vol_7, ["incoming_javelin_hit_ground_1.wav"]),
   ("outgoing_knife_hit_ground",sf_priority_7|sf_vol_7, ["incoming_stone_hit_ground_1.wav"]),
   ("outgoing_bullet_hit_ground",sf_priority_7|sf_vol_7, ["incoming_bullet_hit_ground_1.wav"]),

   ("draw_sword",sf_priority_2|sf_vol_4, ["draw_sword.wav"]),
   ("put_back_sword",sf_priority_1|sf_vol_4, ["put_back_sword.wav"]),
   ("draw_greatsword",sf_priority_2|sf_vol_4, ["draw_greatsword.wav"]),
   ("put_back_greatsword",sf_priority_1|sf_vol_4, ["put_back_sword.wav"]),
   ("draw_axe",sf_priority_2|sf_vol_4, ["draw_mace.wav"]),
   ("put_back_axe",sf_priority_1|sf_vol_4, ["put_back_to_holster.wav"]),
   ("draw_greataxe",sf_priority_2|sf_vol_4, ["draw_greataxe.wav"]),
   ("put_back_greataxe",sf_priority_1|sf_vol_4, ["put_back_to_leather.wav"]),
   ("draw_spear",sf_priority_2|sf_vol_4, ["draw_spear.wav"]),
   ("put_back_spear",sf_priority_1|sf_vol_4, ["put_back_to_leather.wav"]),
   ("draw_crossbow",sf_priority_2|sf_vol_4, ["draw_crossbow.wav"]),
   ("put_back_crossbow",sf_priority_1|sf_vol_4, ["put_back_to_leather.wav"]),
   ("draw_revolver",sf_priority_2|sf_vol_4, ["draw_from_holster.wav"]),
   ("put_back_revolver",sf_priority_1|sf_vol_4, ["put_back_to_holster.wav"]),
   ("draw_dagger",sf_priority_2|sf_vol_4, ["draw_dagger.wav"]),
   ("put_back_dagger",sf_priority_1|sf_vol_4, ["put_back_dagger.wav"]),
   ("draw_bow",sf_priority_2|sf_vol_4, ["draw_bow.wav"]),
   ("put_back_bow",sf_priority_1|sf_vol_4, ["put_back_to_holster.wav"]),
   ("draw_shield",sf_priority_2|sf_vol_4, ["draw_shield.wav"]),
   ("put_back_shield",sf_priority_1|sf_vol_4, ["put_back_shield.wav"]),
   ("draw_other",sf_priority_2|sf_vol_4, ["draw_other.wav"]),
   ("put_back_other",sf_priority_1|sf_vol_4, ["draw_other2.wav"]),
   ("body_fall_small",sf_priority_5|sf_vol_9, ["body_fall_small_1.wav","body_fall_small_2.wav"]),
   ("body_fall_big",sf_priority_6|sf_vol_8, ["body_fall_1.wav","body_fall_2.wav","body_fall_3.wav"]),
   ("horse_body_fall_begin",sf_priority_6|sf_vol_10, ["horse_body_fall_begin_1.wav"]),
   ("horse_body_fall_end",sf_priority_6|sf_vol_10, ["horse_body_fall_end_1.wav","body_fall_2.wav","horse_fall_e_03.wav"]),
   ("hit_wood_wood",sf_priority_7|sf_vol_12, ["hit_wood_wood_1.wav","hit_wood_wood_2.wav","hit_wood_wood_3.wav","hit_wood_wood_4.wav","hit_wood_metal_4.wav","hit_wood_metal_5.wav","hit_wood_metal_6.wav"]),#dummy
   ("hit_metal_metal",sf_priority_7|sf_vol_10, ["hit_metal_metal_3.wav","hit_metal_metal_4.wav","hit_metal_metal_5.wav","hit_metal_metal_6.wav","hit_metal_metal_7.wav","hit_metal_metal_8.wav","hit_metal_metal_9.wav","hit_metal_metal_10.wav","clang_metal_1.wav","clang_metal_2.wav"]),
   ("hit_wood_metal",sf_priority_7|sf_vol_10, ["hit_metal_metal_1.wav","hit_metal_metal_2.wav","hit_wood_metal_7.wav"]),
   ("shield_hit_wood_wood",sf_priority_7|sf_vol_9, ["shield_hit_wood_wood_1.wav","shield_hit_wood_wood_2.wav","shield_hit_wood_wood_3.wav"]),
   ("shield_hit_metal_metal",sf_priority_7|sf_vol_10, ["shield_hit_metal_metal_1.wav","shield_hit_metal_metal_2.wav","shield_hit_metal_metal_3.wav","shield_hit_metal_metal_4.wav"]),
   ("shield_hit_wood_metal",sf_priority_7|sf_vol_10, ["shield_hit_cut_3.wav","shield_hit_cut_4.wav","shield_hit_cut_5.wav","shield_hit_cut_10.wav"]), #(shield is wood)
   ("shield_hit_metal_wood",sf_priority_7|sf_vol_10, ["shield_hit_metal_wood_1.wav","shield_hit_metal_wood_2.wav","shield_hit_metal_wood_3.wav"]),#(shield is metal)
   ("shield_broken",sf_priority_9, ["shield_broken.wav"]),
   ("man_hit",sf_priority_7|sf_vol_7, ["man_hit_5.wav","man_hit_6.wav","man_hit_7.wav","man_hit_8.wav","man_hit_9.wav","man_hit_10.wav","man_hit_11.wav","man_hit_12.wav","man_hit_13.wav","man_hit_14.wav","man_hit_15.wav","man_hit_17.wav","man_hit_18.wav","man_hit_19.wav","man_hit_22.wav","man_hit_29.wav","man_hit_32.wav","man_hit_47.wav","man_hit_57.wav","man_hit_59.wav"]),
   ("man_die",sf_priority_10|sf_vol_8,  ["man_death_1.wav","man_death_8.wav","man_death_8b.wav","man_death_11.wav","man_death_14.wav","man_death_16.wav","man_death_18.wav","man_death_21.wav","man_death_29.wav","man_death_40.wav","man_death_44.wav","man_death_46.wav","man_death_48.wav","man_death_64.wav"]),# ["man_fall_1.wav","man_fall_2.wav","man_fall_3.wav","man_fall_4.wav"]),
   ("woman_hit",sf_priority_7, ["woman_hit_2.wav","woman_hit_3.wav","woman_hit_b_2.wav","woman_hit_b_4.wav","woman_hit_b_6.wav","woman_hit_b_7.wav","woman_hit_b_8.wav","woman_hit_b_11.wav","woman_hit_b_14.wav","woman_hit_b_16.wav"]),
   ("woman_die",sf_priority_10|sf_vol_9, ["woman_death_3.wav","woman_death_4.wav","woman_death_5.wav","woman_death_6.wav","woman_death_7.wav","woman_death_8.wav","woman_death_9.wav","woman_death_10.wav","woman_death_11.wav","woman_death_12.wav","woman_death_13.wav","woman_death_14.wav","woman_death_15.wav"]),
   ("woman_yell",sf_priority_8|sf_vol_9, ["woman_yell_1.wav","woman_yell_2.wav"]),
   ("hide",sf_stream_from_hd, ["s_hide.wav"]),
   ("unhide",sf_stream_from_hd, ["s_unhide.wav"]),
   ("neigh",sf_stream_from_hd, ["horse_exterior_whinny_01.wav","horse_exterior_whinny_02.wav","horse_exterior_whinny_03.wav","horse_exterior_whinny_04.wav","horse_exterior_whinny_05.wav","horse_whinny.wav"]),
   ("gallop",sf_vol_4, ["horse_gallop_3.wav","horse_gallop_4.wav","horse_gallop_5.wav"]),
   ("battle",sf_vol_4|sf_stream_from_hd, ["battle.wav","battle_2.wav"]),
   ("arrow_hit_body",sf_priority_4, ["arrow_hit_body_1.wav","arrow_hit_body_2.wav","arrow_hit_body_3.wav"]),
   ("bullet_hit_body",sf_priority_4, ["missile_flesh_01.wav","missile_flesh_02.wav","missile_flesh_03.wav","missile_flesh_04.wav","missile_flesh_05.wav","missile_flesh_06.wav","missile_flesh_07.wav","missile_flesh_08.wav"]),
   ("metal_hit_low_armor_low_damage",sf_priority_5|sf_vol_9, ["meleeimpact11.wav","meleeimpact12.wav","meleeimpact13.wav","meleeimpact14.wav","meleeimpact15.wav","meleeimpact16.wav","meleeimpact17.wav"]),
   ("metal_hit_low_armor_high_damage",sf_priority_5|sf_vol_9, ["meleeimpact1.wav","meleeimpact2.wav","meleeimpact3.wav","meleeimpact4.wav","meleeimpact5.wav","meleeimpact6.wav","meleeimpact7.wav","meleeimpact8.wav","meleeimpact9.wav","meleeimpact10.wav"]),
   ("metal_hit_high_armor_low_damage", sf_priority_5|sf_vol_9, ["metal_high_low_01.wav", "metal_high_low_02.wav", "metal_high_low_03.wav", "metal_high_low_04.wav", "metal_high_low_05.wav", "metal_high_low_06.wav", "metal_high_low_07.wav", "metal_high_low_08.wav", "metal_high_low_09.wav", "metal_high_low_10.wav", "metal_high_low_11.wav", "metal_high_low_12.wav", "metal_high_low_13.wav", "metal_high_low_14.wav", "metal_high_low_15.wav", "metal_high_low_16.wav", "metal_high_low_17.wav", "metal_high_low_18.wav", "metal_high_low_19.wav", "metal_high_low_20.wav", "metal_high_low_21.wav", "metal_high_low_22.wav", "metal_high_low_23.wav", "metal_high_low_24.wav", "metal_high_low_25.wav"]),
   ("metal_hit_high_armor_high_damage", sf_priority_5|sf_vol_9, ["metal_high_high_01.wav", "metal_high_high_02.wav", "metal_high_high_03.wav", "metal_high_high_04.wav", "metal_high_high_05.wav", "metal_high_high_06.wav", "metal_high_high_07.wav", "metal_high_high_08.wav", "metal_high_high_09.wav", "metal_high_high_10.wav", "metal_high_high_11.wav", "metal_high_high_12.wav", "metal_high_high_13.wav", "metal_high_high_14.wav", "metal_high_high_15.wav", "metal_high_high_16.wav", "metal_high_high_17.wav", "metal_high_high_18.wav", "metal_high_high_19.wav", "metal_high_high_20.wav", "metal_high_high_21.wav", "metal_high_high_22.wav", "metal_high_high_23.wav", "metal_high_high_24.wav", "metal_high_high_25.wav", "metal_high_high_26.wav", "metal_high_high_27.wav", "metal_high_high_28.wav", "metal_high_high_29.wav", "metal_high_high_30.wav", "metal_high_high_31.wav", "metal_high_high_32.wav"]),
   ("wooden_hit_low_armor_low_damage",sf_priority_5|sf_vol_9, ["blunt_hit_low_1.wav","blunt_hit_low_2.wav","blunt_hit_low_3.wav"]),
   ("wooden_hit_low_armor_high_damage",sf_priority_5|sf_vol_9, ["blunt_hit_high_1.wav","blunt_hit_high_2.wav","blunt_hit_high_3.wav"]),
   ("wooden_hit_high_armor_low_damage",sf_priority_5|sf_vol_9, ["blunt_high_low_01.wav","wooden_hit_high_armor_low_damage_2.wav"]),
   ("wooden_hit_high_armor_high_damage",sf_priority_5|sf_vol_9, ["blunt_hit_high_1.wav","blunt_hit_high_2.wav","blunt_hit_high_3.wav"]),
   ("mp_arrow_hit_target",sf_2d|sf_priority_15|sf_vol_9|sf_stream_from_hd, ["mp_arrow_hit_target.wav"]),
   ("blunt_hit",sf_priority_5|sf_vol_9, ["punch_1.wav","punch_4.wav","punch_4.wav","punch_5.wav"]),
   ("player_hit_by_bullet",sf_priority_11|sf_vol_10, ["player_hit_by_arrow.wav"]),
   ("player_hit_by_arrow",sf_priority_10|sf_vol_10, ["player_hit_by_arrow.wav"]),
   ("pistol_shot",sf_priority_10|sf_vol_10, ["fl_pistol.wav"]),

   ("man_grunt",sf_priority_6|sf_vol_4, ["man_excercise_1.wav","man_excercise_2.wav","man_excercise_4.wav"]),
   ("man_breath_hard",sf_priority_3|sf_vol_8, ["man_ugh_1.wav","man_ugh_2.wav","man_ugh_4.wav","man_ugh_7.wav","man_ugh_12.wav","man_ugh_13.wav","man_ugh_17.wav"]),
   ("man_stun",sf_priority_3|sf_vol_8, ["man_stun_1.wav"]),
   ("man_grunt_long",sf_priority_6|sf_vol_7, ["man_grunt_1.wav","man_grunt_2.wav","man_grunt_3.wav","man_grunt_5.wav","man_grunt_13.wav","man_grunt_14.wav"]),
   ("man_yell",sf_priority_5|sf_vol_8, ["man_yell_4.wav","man_yell_4_2.wav","man_yell_7.wav","man_yell_9.wav","man_yell_11.wav","man_yell_13.wav","man_yell_15.wav","man_yell_16.wav","man_yell_17.wav","man_yell_20.wav","man_shortyell_4.wav","man_shortyell_5.wav","man_shortyell_6.wav","man_shortyell_9.wav","man_shortyell_11.wav","man_shortyell_11b.wav","man_yell_b_18.wav","man_yell_22.wav", "man_yell_c_20.wav"]),
   ("man_warcry",sf_priority_5, ["man_insult_2.wav","man_insult_3.wav","man_insult_7.wav","man_insult_9.wav","man_insult_13.wav","man_insult_15.wav","man_insult_16.wav"]),

   ("encounter_looters",sf_2d|sf_vol_8|sf_stream_from_hd, ["encounter_river_pirates_5.wav","encounter_river_pirates_6.wav","encounter_river_pirates_9.wav","encounter_river_pirates_10.wav","encounter_river_pirates_4.wav"]),
   ("encounter_bandits",sf_2d|sf_vol_8|sf_stream_from_hd, ["encounter_bandit_2.wav","encounter_bandit_9.wav","encounter_bandit_12.wav","encounter_bandit_13.wav","encounter_bandit_15.wav","encounter_bandit_16.wav","encounter_bandit_10.wav",]),
   ("encounter_farmers",sf_2d|sf_vol_8|sf_stream_from_hd, ["encounter_farmer_2.wav","encounter_farmer_5.wav","encounter_farmer_7.wav","encounter_farmer_9.wav"]),
   ("encounter_sea_raiders",sf_2d|sf_vol_8|sf_stream_from_hd, ["encounter_sea_raider_5.wav","encounter_sea_raider_9.wav","encounter_sea_raider_9b.wav","encounter_sea_raider_10.wav"]),
   ("encounter_steppe_bandits",sf_2d|sf_vol_8|sf_stream_from_hd, ["encounter_steppe_bandit_3.wav","encounter_steppe_bandit_3b.wav","encounter_steppe_bandit_8.wav","encounter_steppe_bandit_10.wav","encounter_steppe_bandit_12.wav"]),
   ("encounter_nobleman",sf_2d|sf_vol_8|sf_stream_from_hd, ["encounter_nobleman_1.wav"]),
   ("encounter_vaegirs_ally",sf_2d|sf_vol_8|sf_stream_from_hd, ["encounter_vaegirs_ally.wav","encounter_vaegirs_ally_2.wav"]),
   ("encounter_vaegirs_neutral",sf_2d|sf_vol_8|sf_stream_from_hd, ["encounter_vaegirs_neutral.wav","encounter_vaegirs_neutral_2.wav","encounter_vaegirs_neutral_3.wav","encounter_vaegirs_neutral_4.wav"]),
   ("encounter_vaegirs_enemy",sf_2d|sf_vol_8|sf_stream_from_hd, ["encounter_vaegirs_neutral.wav","encounter_vaegirs_neutral_2.wav","encounter_vaegirs_neutral_3.wav","encounter_vaegirs_neutral_4.wav"]),
   ("sneak_town_halt",sf_2d|sf_stream_from_hd, ["sneak_halt_1.wav","sneak_halt_2.wav"]),

   ("horse_walk",sf_priority_3|sf_vol_5, ["horse_walk_1.wav","horse_walk_2.wav","horse_walk_3.wav","horse_walk_4.wav"]),
   ("horse_trot",sf_priority_4|sf_vol_6, ["horse_trot_1.wav","horse_trot_2.wav","horse_trot_3.wav","horse_trot_4.wav"]),
   ("horse_canter",sf_priority_4|sf_vol_7, ["horse_canter_1.wav","horse_canter_2.wav","horse_canter_3.wav","horse_canter_4.wav"]),
   ("horse_gallop",sf_priority_5|sf_vol_8, ["horse_gallop_6.wav","horse_gallop_7.wav","horse_gallop_8.wav","horse_gallop_9.wav"]),
   ("horse_breath",sf_priority_1|sf_vol_4, ["horse_breath_4.wav","horse_breath_5.wav","horse_breath_6.wav","horse_breath_7.wav"]),
   ("horse_snort",sf_priority_1|sf_vol_2, ["horse_snort_1.wav","horse_snort_2.wav","horse_snort_3.wav","horse_snort_4.wav","horse_snort_5.wav"]),
   ("horse_low_whinny",sf_vol_12, ["horse_whinny-1.wav","horse_whinny-2.wav"]),
   ("block_fist",0, ["block_fist_3.wav","block_fist_4.wav"]),
   ("man_hit_blunt_weak",sf_priority_5|sf_vol_10, ["man_hit_13.wav","man_hit_29.wav","man_hit_32.wav","man_hit_47.wav","man_hit_57.wav"]),
   ("man_hit_blunt_strong",sf_priority_5|sf_vol_10, ["man_hit_13.wav","man_hit_29.wav","man_hit_32.wav","man_hit_47.wav","man_hit_57.wav"]),
   ("man_hit_pierce_weak",sf_priority_5|sf_vol_10, ["man_hit_13.wav","man_hit_29.wav","man_hit_32.wav","man_hit_47.wav","man_hit_57.wav"]),
   ("man_hit_pierce_strong",sf_priority_5|sf_vol_10, ["man_hit_13.wav","man_hit_29.wav","man_hit_32.wav","man_hit_47.wav","man_hit_57.wav"]),
   ("man_hit_cut_weak",sf_priority_5|sf_vol_10, ["man_hit_13.wav","man_hit_29.wav","man_hit_32.wav","man_hit_47.wav","man_hit_57.wav"]),
   ("man_hit_cut_strong",sf_priority_5|sf_vol_10, ["man_hit_13.wav","man_hit_29.wav","man_hit_32.wav","man_hit_47.wav","man_hit_57.wav"]),
   ("man_victory",sf_priority_5|sf_vol_10, ["man_victory_3.wav","man_victory_4.wav","man_victory_5.wav","man_victory_8.wav","man_victory_15.wav","man_victory_49.wav","man_victory_52.wav","man_victory_54.wav","man_victory_57.wav","man_victory_71.wav"]),
   ("torch_loop",sf_priority_9|sf_vol_4|sf_looping|sf_start_at_random_pos|sf_stream_from_hd, ["Fire_Torch_Loop3.wav","Fire_Torch_Loop3_new.wav"]),
   ("dummy_hit",sf_priority_9|sf_stream_from_hd, ["shield_hit_cut_3.wav","shield_hit_cut_5.wav"]),
   ("dummy_destroyed",sf_priority_9|sf_stream_from_hd, ["shield_broken.wav"]),
   ("gourd_destroyed",sf_priority_9|sf_stream_from_hd, ["shield_broken.wav"]),#TODO
   ("cow_moo", sf_2d|sf_priority_9|sf_vol_8|sf_stream_from_hd, ["cow_moo_1.wav"]),
   ("cow_slaughter", sf_2d|sf_priority_9|sf_vol_8|sf_stream_from_hd, ["cow_slaughter.wav"]),
   ("distant_dog_bark", sf_2d|sf_priority_3|sf_vol_8|sf_stream_from_hd, ["d_dog1.wav","d_dog2.wav","d_dog3.wav","d_dog7.wav"]),
   ("distant_owl", sf_2d|sf_priority_3|sf_vol_9|sf_stream_from_hd, ["d_owl2.wav","d_owl3.wav","d_owl4.wav"]),
   ("distant_chicken", sf_2d|sf_priority_3|sf_vol_8|sf_stream_from_hd, ["d_chicken1.wav","d_chicken2.wav"]),
   ("distant_carpenter", sf_2d|sf_priority_3|sf_vol_3|sf_stream_from_hd, ["d_carpenter1.wav","d_saw_short3.wav"]),
   ("distant_blacksmith", sf_2d|sf_priority_3|sf_vol_4|sf_stream_from_hd, ["d_blacksmith2.wav"]),
   ("arena_ambiance", sf_2d|sf_priority_8|sf_vol_3|sf_looping|sf_stream_from_hd, ["arena_loop10.wav"]),
   ("town_ambiance", sf_2d|sf_priority_8|sf_vol_3|sf_looping|sf_stream_from_hd, ["town_loop_3.wav"]),
   ("tutorial_fail", sf_2d|sf_vol_7|sf_stream_from_hd,["cue_failure.wav"]),
   ("team_scored_a_point", sf_2d|sf_priority_10|sf_vol_10|sf_stream_from_hd, ["you_scored_a_point.wav"]),
   ("dedal_tavern_lute",	sf_priority_8|sf_vol_15|sf_looping|sf_stream_from_hd, ["rome_lyre.wav"]),
   ("dedal_tavern_lyre",	sf_priority_8|sf_vol_15|sf_looping|sf_stream_from_hd, ["greece_lyre.wav"]),
   ("dedal_tavern_flute",	sf_priority_8|sf_vol_10|sf_looping|sf_stream_from_hd, ["fleita.wav","fleita1.wav"]),
   ("dedal_mine_pickaxe",	sf_priority_8|sf_vol_15|sf_looping|sf_stream_from_hd, ["pickaxesound.wav"]),
   ("woman_grunt",sf_priority_6|sf_vol_5|sf_stream_from_hd, ["femgrunt5.wav","femgrunt6.wav","femgrunt8.wav","gruntfem3.wav","fem_attack.wav"]),
   ("woman_stun",sf_priority_3|sf_vol_8|sf_stream_from_hd, ["gruntfem1.wav","gruntfem7.wav","wgrunt4.wav"]),
   ("woman_grunt_long",sf_priority_6|sf_vol_7|sf_stream_from_hd, ["femgrunt1.wav","femgrunt2.wav","femgrunt9.wav","femgrunt10.wav"]),
   ("woman_victory",sf_priority_5|sf_vol_10|sf_stream_from_hd, ["wooaao.wav","womancheer1.wav","femalecheer3.wav","femalecheer4.wav","femalecheer5.wav","womanlaugh.wav","ribaude_1.wav"]),
   ("thunder_close", sf_2d|sf_priority_10|sf_vol_10|sf_stream_from_hd, ["thunder_close_1.wav","thunder_close_2.wav","thunder_close_3.wav", "thunder.wav"]),
   ("panic_cry", sf_priority_10|sf_vol_10|sf_stream_from_hd,["male_scream_02.wav", "male_scream_04.wav"]),
   ("panic_hit", sf_priority_9|sf_vol_10|sf_stream_from_hd,["yell_pain_male_06.wav", "yell_pain_male_11.wav"]),
   ("missile_dive", sf_priority_5|sf_vol_8|sf_stream_from_hd, ["missile_dive.wav"]),
   ("male_misc",sf_priority_5|sf_vol_5|sf_stream_from_hd,["male_misc_1.wav","male_misc_2.wav","male_misc_3.wav","male_misc_4.wav","male_misc_5.wav","male_misc_6.wav","male_misc_7.wav"]),
   ("male_sigh",sf_priority_5|sf_vol_5|sf_stream_from_hd,["male_sigh_1.wav","male_sigh_2.wav","male_sigh_3.wav","male_sigh_4.wav"]),
   ("female_misc",sf_priority_5|sf_vol_5|sf_stream_from_hd,["female_misc_1.wav","female_misc_2.wav","female_misc_3.wav","female_misc_4.wav","female_misc_5.wav","female_misc_6.wav","female_misc_7.wav","female_misc_8.wav","female_misc_9.wav"]),
   ("female_sigh",sf_priority_5|sf_vol_5|sf_stream_from_hd,["female_sigh_1.wav","female_sigh_2.wav","female_sigh_3.wav","female_sigh_4.wav","female_sigh_5.wav","female_sigh_6.wav","female_sigh_7.wav"]),
   ("ambient_day_plains_loop", sf_2d|sf_priority_6|sf_vol_5|sf_looping|sf_stream_from_hd, ["ambient_day_plains_loop_1.wav","ambient_day_plains_loop_2.wav","ambient_day_plains_loop_3.wav","country_ambience.wav"]),
   ("ambient_day_forest_loop", sf_2d|sf_priority_6|sf_vol_5|sf_looping|sf_stream_from_hd, ["ambient_day_plains_loop_1.wav","ambient_day_plains_loop_2.wav","ambient_day_plains_loop_3.wav"]),
   ("ambient_day_village_loop", sf_2d|sf_priority_6|sf_vol_5|sf_looping|sf_stream_from_hd, ["ambient_day_plains_loop_1.wav","ambient_day_plains_loop_2.wav","ambient_day_plains_loop_3.wav"]),
   ("ambient_sea_loop", sf_2d|sf_priority_6|sf_vol_8|sf_looping|sf_stream_from_hd, ["sea_loop.wav","oceansurf01.wav","oceansurf02.wav"]),
   ("ambient_night_loop", sf_2d|sf_priority_6|sf_vol_5|sf_looping|sf_stream_from_hd, ["ambient_night_loop_1.wav","ambient_night_loop_2.wav","ambient_night_loop_3.wav"]),
   ("ambient_tavern_loop", sf_2d|sf_priority_6|sf_vol_3|sf_looping|sf_stream_from_hd, ["ambient_tavern_loop.wav","outdoor_market_small_town.wav"]),
   ("ambient_random_plains", sf_2d|sf_priority_6|sf_vol_7|sf_stream_from_hd, ["ambient_random_bird_1.wav","ambient_random_bird_2.wav","ambient_random_bird_3.wav","ambient_random_bird_4.wav","morning_birds.wav","ambient_random_crow_1.wav","ambient_random_crow_2.wav","ambient_random_crow_3.wav",]),
   ("ambient_random_forest", sf_2d|sf_priority_6|sf_vol_7|sf_stream_from_hd, ["ambient_random_bird_1.wav","ambient_random_bird_2.wav","ambient_random_bird_3.wav","ambient_random_bird_4.wav","ambient_random_crow_1.wav","ambient_random_crow_2.wav","ambient_random_crow_3.wav","morning_birds.wav"]),
   ("ambient_random_village", sf_2d|sf_priority_6|sf_vol_7|sf_stream_from_hd, ["ambient_random_dog_1.wav","ambient_random_dog_2.wav","ambient_random_dog_3.wav","ambient_random_dog_4.wav","ambient_random_dog_5.wav","ambient_random_dog_6.wav","ambient_random_chicken_1.wav","ambient_random_chicken_2.wav","ambient_random_chicken_3.wav","ambient_random_chicken_4.wav","ambient_random_chicken_5.wav","ambient_random_bird_1.wav","ambient_random_bird_2.wav","ambient_random_bird_3.wav","ambient_random_bird_4.wav","ambient_random_cow_1.wav","ambient_random_cow_2.wav","ambient_random_cow_3.wav","ambient_random_cow_4.wav","ambient_random_cow_5.wav","ambient_random_crow_1.wav","ambient_random_crow_2.wav","ambient_random_crow_3.wav","morning_birds.wav"]),
   ("ambient_random_sea", sf_2d|sf_priority_6|sf_vol_6|sf_stream_from_hd, ["oceansurf01.wav","oceansurf02.wav"]),
   ("ambient_random_night", sf_2d|sf_priority_6|sf_vol_6|sf_stream_from_hd, ["d_owl2.wav","d_owl3.wav","d_owl4.wav"]),
   ("ambient_random_town", sf_2d|sf_priority_6|sf_vol_7|sf_stream_from_hd, ["ambient_random_dog_1.wav","ambient_random_dog_2.wav","ambient_random_dog_3.wav","ambient_random_dog_4.wav","ambient_random_dog_5.wav","ambient_random_dog_6.wav","ambient_random_chicken_1.wav","ambient_random_chicken_2.wav","ambient_random_chicken_3.wav","ambient_random_chicken_4.wav","ambient_random_chicken_5.wav","ambient_random_bird_1.wav","ambient_random_bird_2.wav","ambient_random_bird_3.wav","ambient_random_bird_4.wav","morning_birds.wav"]),
   ("ambient_random_tavern", sf_2d|sf_priority_6|sf_vol_6|sf_stream_from_hd, ["male_misc_1.wav","male_misc_2.wav","male_misc_3.wav","male_misc_4.wav","male_misc_5.wav","male_misc_6.wav","male_misc_7.wav"]),
   ("ambient_coast_loop", sf_2d|sf_priority_1|sf_vol_1|sf_looping|sf_stream_from_hd, ["coastal_ambience.wav"]),
   ("seagull", sf_2d|sf_priority_5|sf_vol_4|sf_stream_from_hd, ["seagull2.wav"]),
   ("distant_worker", sf_2d|sf_priority_6|sf_vol_3|sf_stream_from_hd, ["d_blacksmith2.wav","d_carpenter1.wav","d_saw_short3.wav"]),
   ("female_laugh",sf_priority_5|sf_vol_5|sf_stream_from_hd|sf_2d,["female_sigh_4.wav","female_sigh_5.wav"]),
   ("female_annoyed",sf_priority_5|sf_vol_5|sf_stream_from_hd|sf_2d,["female_sigh_1.wav","female_sigh_2.wav","female_sigh_3.wav"]),
   ("female_bored",sf_priority_5|sf_vol_5|sf_stream_from_hd|sf_2d,["female_sigh_7.wav"]),
   ("horn", sf_priority_15|sf_vol_15|sf_stream_from_hd|sf_2d,["horn.wav","kwazi_epic_war_horns_02_high.wav","kwazi_epic_war_horns_02_low.wav","hedmarking__prillarhorn.wav"]),
   ("inmersive_troops",sf_priority_9|sf_vol_10|sf_stream_from_hd, ["immersive_susurros.wav","immersive_ahem.wav","immersive_burp.wav","immersive_cough_clears.wav","immersive_farties.wav","immersive_whistle.wav","immersive_coughs.wav","immersive_crowdwhispers.wav"]),
   ("inmersive_troops_cv",sf_priority_9|sf_vol_10|sf_stream_from_hd, ["immersive_short_burp.wav","immersive_sorbos.wav","immersive_coughings.wav","immersive_clearing_throat.wav","immersive_farts.wav","immersive_chantl.wav","immersive_chants.wav","immersive_chantsp.wav"]),
   ("shield_taunt", sf_priority_8|sf_vol_5|sf_stream_from_hd,["shield_taunt.wav"]),
   ("water",sf_priority_5|sf_vol_6|sf_stream_from_hd, ["water_splash_03.wav"]),
   ("man_scream",sf_priority_8|sf_vol_6|sf_stream_from_hd|sf_2d, ["yell_pain_male_06.wav"]),
   ("aaa_scream",sf_priority_8|sf_vol_6|sf_stream_from_hd|sf_2d, ["man_die_06.wav"]),

   ("pickaxesound",sf_2d|sf_vol_6|sf_stream_from_hd, ["pickaxesound.wav"]),
   ("schiff_liegt",sf_2d|sf_vol_6|sf_stream_from_hd, ["schiff_liegt.wav"]),
   ("cornu",sf_priority_15|sf_vol_15|sf_stream_from_hd, ["cornu_1.wav","cornu_2.wav"]),
   ("senatus_sound_1",sf_priority_9|sf_vol_15|sf_stream_from_hd, ["senate_1.wav"]),
   ("senatus_sound_2",sf_priority_9|sf_vol_15|sf_stream_from_hd, ["senate_2.wav"]),
   ("message_negative_sound",sf_priority_9|sf_vol_5|sf_stream_from_hd, ["message_negative_sound.wav"]),
   ("disease_sound",sf_priority_9|sf_vol_5|sf_stream_from_hd, ["disease_sound.wav"]),
   ("riot_sound",sf_priority_9|sf_vol_5|sf_stream_from_hd, ["riot_sound.wav"]),
   ("fire", sf_priority_5|sf_vol_12|sf_stream_from_hd, ["fire1.wav","fire2.wav"]),
   ("harvesting_season", sf_priority_5|sf_vol_12|sf_stream_from_hd, ["encounter_farmer_2.wav"]),
   ("elephant", sf_priority_10|sf_vol_15, ["elephant1.wav"]),
   ("wild_cat", sf_priority_10|sf_vol_15, ["tiger_roar_02.wav","tiger_roar_01.wav","tiger.wav"]),
   ("wolf", sf_priority_10|sf_vol_15, ["wolf.wav","wolf_2.wav"]),
   ("order_charge", sf_priority_15|sf_vol_8|sf_stream_from_hd, ["order_charge.wav","order_charge_2.wav","order_charge_3.wav","order_charge_4.wav","order_charge_5.wav","order_charge_6.wav",]),
   ("order_hold", sf_priority_15|sf_vol_8|sf_stream_from_hd, ["order_hold.wav","order_hold_2.wav","order_hold_3.wav","order_hold_4.wav","order_hold_5.wav",]),
   ("order_fire", sf_priority_15|sf_vol_8|sf_stream_from_hd, ["order_fire.wav","order_fire_2.wav","order_fire_3.wav","order_fire_4.wav","order_fire_5.wav",]),
   ("order_hold_fire", sf_priority_15|sf_vol_8|sf_stream_from_hd, ["order_hold_fire.wav","order_hold_fire_2.wav","order_hold_fire_3.wav",]),
   ("order_stand_closer", sf_priority_15|sf_vol_8|sf_stream_from_hd, ["order_stand_closer.wav",]),
   ("order_spread", sf_priority_15|sf_vol_8|sf_stream_from_hd, ["order_spread.wav",]),
   ("order_retreat", sf_priority_15|sf_vol_8|sf_stream_from_hd, ["order_retreat.wav",]),

   ("intro_1", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["intro_1.wav",]),
   ("intro_2", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["intro_2.wav",]),
   ("intro_3", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["intro_3.wav",]),
   ("intro_4", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["intro_4.wav",]),
   ("intro_5", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["intro_5.wav",]),
   ("intro_6", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["intro_6.wav",]),

   # speech player, voice lucas, clarity 0.75, variability 0.95
   ("player_speech_rome_other_goy", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["player_speech_rome_other_goy.wav",]),

   ("battle_speech_1", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["battle_speech_1.wav",]),
   ("battle_speech_2", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["battle_speech_2.wav",]),
   ("battle_speech_3", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["battle_speech_3.wav",]),
   ("battle_speech_4", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["battle_speech_4.wav",]),
   ("battle_speech_5", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["battle_speech_5.wav",]),
   ("battle_speech_6", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["battle_speech_6.wav",]),
   ("battle_speech_7", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["battle_speech_7.wav",]),
   ("battle_speech_8", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["battle_speech_8.wav",]),
   ("battle_speech_9", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["battle_speech_9.wav",]),
   ("battle_speech_10", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["battle_speech_10.wav",]),
   ("battle_speech_11", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["battle_speech_11.wav",]),

   ("antonia_speech_1", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["antonia_speech_1.wav",]),
   ("antonia_speech_2", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["antonia_speech_2.wav",]),
   ("antonia_speech_3", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["antonia_speech_3.wav",]),
   ("antonia_speech_4", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["antonia_speech_4.wav",]),
   ("antonia_speech_5", sf_priority_15|sf_vol_15|sf_stream_from_hd, ["antonia_speech_5.wav",]),

   ("baths_spring", sf_priority_5|sf_vol_15|sf_stream_from_hd, ["baths_spring.wav",]),
   ("scream_warcry",sf_priority_8|sf_vol_15|sf_stream_from_hd, ["man_insult_13.wav"]),
]
