name: Deploy static content to Pages

on:
  push:
    branches: ["develop"]
    paths:
      - 'website/**'

  workflow_run:
    workflows: ["Create Pre-Release"]
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      releases: read     # Grant permission for the 'gh release' command

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release info
        id: latest_release
        run: |
          LATEST_TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          MOD_URL=$(gh release view $LATEST_TAG --json assets --jq '.assets[] | select(.name | startswith("ACAN")).browser_download_url')
          MANUAL_URL=$(gh release view $LATEST_TAG --json assets --jq '.assets[] | select(.name == "handbook.pdf").browser_download_url')
          
          echo "VERSION=${LATEST_TAG#v}" >> $GITHUB_OUTPUT
          echo "MOD_URL=$MOD_URL" >> $GITHUB_OUTPUT
          echo "MANUAL_URL=$MANUAL_URL" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update placeholders in index.html
        run: |
          sed -i 's|__MOD_VERSION__|${{ steps.latest_release.outputs.VERSION }}|g' website/index.html
          sed -i 's|__MOD_DOWNLOAD_URL__|${{ steps.latest_release.outputs.MOD_URL }}|g' website/index.html
          sed -i 's|__MANUAL_DOWNLOAD_URL__|${{ steps.latest_release.outputs.MANUAL_URL }}|g' website/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './website'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4